/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/albums": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Albums
         * @description The albums a film can be made from, largest first; `--from-album` takes the id.
         */
        get: operations["albums_api_v1_albums_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Thumbnail
         * @description The picture at grid or preview size; a miss is fetched from Immich and kept.
         */
        get: operations["thumbnail_api_v1_assets__asset_id__thumbnail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/video": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Video
         * @description The playback rendition, streamed by byte range so the preview can seek to the cut's interval.
         */
        get: operations["video_api_v1_assets__asset_id__video_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/automation/attempts/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Attempt
         * @description Where an automation attempt stands, and the run it opened, even a failed one.
         */
        get: operations["read_attempt_api_v1_automation_attempts__attempt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Caches
         * @description What each cache holds on disk.
         */
        get: operations["caches_api_v1_caches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/caches/{name}/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Cache
         * @description Empty one cache; the next run fills it again as it needs.
         */
        post: operations["clear_cache_api_v1_caches__name__clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active Config
         * @description The configuration this server runs with, env overrides applied, secrets masked.
         */
        get: operations["active_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Connection
         * @description The server this install reads, and whether a key is stored for it.
         */
        get: operations["read_connection_api_v1_connection_get"];
        /**
         * Save Connection
         * @description Keep the server and key in the config file the process reads.
         */
        put: operations["save_connection_api_v1_connection_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connection/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Ask the server who the key belongs to, without saving anything.
         */
        post: operations["test_connection_api_v1_connection_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cuts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Cut
         * @description Cut this brief with `generate --no-render`; the job ends with the run the cut became.
         */
        post: operations["start_cut_api_v1_cuts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cuts/command": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cut Command
         * @description The command this brief stands for, as the page offers it to copy.
         */
        post: operations["cut_command_api_v1_cuts_command_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/holidays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Holidays
         * @description The holidays the pipeline resolves, named in the page's language; any MM-DD works too.
         */
        get: operations["holidays_api_v1_holidays_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/i18n": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Messages
         * @description The browser's language, or the one the viewer chose; a missing string falls back to English.
         */
        get: operations["messages_api_v1_i18n_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active Job
         * @description The job running now, for a page that opens mid-cut to join it.
         */
        get: operations["active_job_api_v1_jobs_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Job
         * @description Where the job is, from its record and the files its child writes.
         */
        get: operations["read_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Stop the job's child, from this tab or any other.
         */
        post: operations["cancel_job_api_v1_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description Server-sent events: the job's view on every change, until it finishes.
         */
        get: operations["job_events_api_v1_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Output
         * @description What the child printed, secrets removed: the reason a failed job gives.
         */
        get: operations["job_output_api_v1_jobs__job_id__output_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/music": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Music
         * @description Keep an uploaded MP3, M4A or WAV for renders to use.
         */
        post: operations["upload_music_api_v1_music_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/music/{music_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Music
         * @description A previewed or uploaded track, for the player.
         */
        get: operations["music_api_v1_music__music_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * People
         * @description Everyone Immich has a name for, alphabetically: the names `--person` takes.
         */
        get: operations["people_api_v1_people_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{person_id}/face": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Face
         * @description A person's face crop at avatar size, fetched from Immich once and cached after.
         */
        get: operations["face_api_v1_people__person_id__face_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pictures/{asset_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide
         * @description The owner's word on one picture, kept across runs: never use it, clear its hold, or forget.
         */
        post: operations["decide_api_v1_pictures__asset_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Roster
         * @description Everyone in the people file, inner circle first, with what needs curating.
         */
        get: operations["roster_api_v1_roster_get"];
        put?: never;
        /**
         * Add
         * @description Add someone Immich has not tagged, or who is never on camera.
         */
        post: operations["add_api_v1_roster_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roster/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Scan People
         * @description Read the library's people again with `people scan`, keeping every answer given.
         */
        post: operations["scan_people_api_v1_roster_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roster/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Answer
         * @description Keep this person's role, notes and answers to the graph's guesses.
         */
        put: operations["answer_api_v1_roster__person_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/roster/{person_id}/relationships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relate
         * @description Record one relationship; the file keeps its reciprocal.
         */
        post: operations["relate_api_v1_roster__person_id__relationships_post"];
        /**
         * Unrelate
         * @description Remove a relationship somebody recorded, and its reciprocal.
         */
        delete: operations["unrelate_api_v1_roster__person_id__relationships_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Runs newest first, each with the first pictures its saved cut plays.
         */
        get: operations["list_runs_api_v1_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Run
         * @description One run as `runs show` reads it: outcome, output, delivery, warnings and phase timings.
         */
        get: operations["read_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/child-output": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Child Output
         * @description The retained output of an automatic run, credentials already removed when it was kept.
         */
        get: operations["child_output_api_v1_runs__run_id__child_output_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/cut": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Cut
         * @description The cut in the order it plays, each shot with every reason the run recorded for it.
         */
        get: operations["read_cut_api_v1_runs__run_id__cut_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/film": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Film
         * @description The rendered film, by byte range so the player can seek.
         */
        get: operations["film_api_v1_runs__run_id__film_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/music-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Music Preview
         * @description Generate the music this cut would get with `music preview`, to hear before rendering.
         */
        post: operations["start_music_preview_api_v1_runs__run_id__music_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Pool
         * @description Every picture the cut saw, in capture order, with its fate and whatever holds it.
         */
        get: operations["read_pool_api_v1_runs__run_id__pool_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/recut": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recut
         * @description Cut the same brief again with the owner's ticks, as `generate --include/--exclude` does.
         */
        post: operations["recut_api_v1_runs__run_id__recut_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/renders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Render
         * @description Render this run's cut, or one revision of it, with `runs render`.
         */
        post: operations["start_render_api_v1_runs__run_id__renders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Report
         * @description Return the same redacted Markdown as the CLI report command (#1428).
         */
        get: operations["read_report_api_v1_runs__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Revisions
         * @description Every saved revision of this cut, oldest first.
         */
        get: operations["list_revisions_api_v1_runs__run_id__revisions_get"];
        put?: never;
        /**
         * Create Revision
         * @description Keep the owner's edits as the next revision; 422 names the edit that would not render.
         */
        post: operations["create_revision_api_v1_runs__run_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/story": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read Story
         * @description The stories the cut tells, heaviest first, each with the pictures that carry it.
         */
        get: operations["read_story_api_v1_runs__run_id__story_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session View
         * @description The provider the sign-in page offers and whether this browser is signed in.
         */
        get: operations["session_view_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/special-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Special Days
         * @description The days `discover-days` catalogued, anniversaries due first, then the rest.
         *
         *     A scheduled run only proposes a day on its anniversary; someone at the brief wants a memory
         *     now, so every catalogued day is offered below the due ones. A day the model could not name
         *     is left out: there is nothing truthful to put on its title card.
         */
        get: operations["special_days_api_v1_special_days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Suggestions
         * @description Up to twenty candidates, and why the others were set aside.
         */
        get: operations["suggestions_api_v1_suggestions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/suggestions/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Suggestion
         * @description Start the candidate as `auto run` would: a lease, an attempt, the real CLI child.
         */
        post: operations["run_suggestion_api_v1_suggestions_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trips
         * @description The trips that overlap a year, as `generate` lists them before it cuts one.
         */
        get: operations["trips_api_v1_trips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActiveConfig */
        ActiveConfig: {
            /** Path */
            path: string;
            /** Preset */
            preset: string | null;
            /** Sections */
            sections: {
                [key: string]: unknown;
            };
        };
        /** AlbumChoice */
        AlbumChoice: {
            /** Asset Count */
            asset_count: number;
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /**
         * Alternative
         * @description Another picture of the shot's moment, eligible when the shot was chosen.
         */
        Alternative: {
            /** Asset Id */
            asset_id: string;
            /** Facts */
            facts: string;
            /** Fate */
            fate: string;
        };
        /** AttemptView */
        AttemptView: {
            /** Id */
            id: string;
            /** Outcome */
            outcome: string;
            /** Phase */
            phase: string | null;
            /** Reason */
            reason: string;
            /** Run Id */
            run_id: string | null;
        };
        /** Body_upload_music_api_v1_music_post */
        Body_upload_music_api_v1_music_post: {
            /** File */
            file: string;
        };
        /** CacheStats */
        CacheStats: {
            /** Bytes */
            bytes: number;
            /** Items */
            items: number;
            /**
             * Name
             * @enum {string}
             */
            name: "analysis" | "video" | "thumbnail" | "preview";
        };
        /** Choice */
        Choice: {
            /** Kind */
            kind: string;
            /** Label */
            label: string;
        };
        /** Cleared */
        Cleared: {
            /**
             * Name
             * @enum {string}
             */
            name: "analysis" | "video" | "thumbnail" | "preview";
            /** Removed */
            removed: number;
        };
        /** Connection */
        Connection: {
            /** Has Key */
            has_key: boolean;
            /** Url */
            url: string;
        };
        /** ConnectionEntry */
        ConnectionEntry: {
            /**
             * Api Key
             * @default
             */
            api_key: string;
            /** Url */
            url: string;
        };
        /** Cut */
        Cut: {
            /** Content Budget Seconds */
            content_budget_seconds: number | null;
            /** Content Seconds */
            content_seconds: number;
            /** Film Seconds */
            film_seconds: number | null;
            /** Model Polish */
            model_polish: boolean;
            /** Run Id */
            run_id: string;
            /** Shots */
            shots: components["schemas"]["CutShot"][];
            /** Thesis */
            thesis: string;
        };
        /**
         * CutBrief
         * @description What to cut; None leaves a flag out, so the CLI's own default applies.
         */
        CutBrief: {
            /**
             * Accept Any Provenance
             * @default false
             */
            accept_any_provenance: boolean;
            /**
             * All Trips
             * @default false
             */
            all_trips: boolean;
            /** Birthday */
            birthday?: string | null;
            /** Day */
            day?: string | null;
            /** Duration */
            duration?: number | null;
            /** End */
            end?: string | null;
            /** Event Id */
            event_id?: string | null;
            /**
             * Exclude Asset
             * @default []
             */
            exclude_asset: string[];
            /** From Album */
            from_album?: string | null;
            /** Hemisphere */
            hemisphere?: ("north" | "south") | null;
            /** Holiday */
            holiday?: string | null;
            /**
             * Include Asset
             * @default []
             */
            include_asset: string[];
            /** Include Live Photos */
            include_live_photos?: boolean | null;
            /** Include Photos */
            include_photos?: boolean | null;
            /** Memory Type */
            memory_type?: string | null;
            /** Month */
            month?: number | null;
            /** Near Date */
            near_date?: string | null;
            /** People Expression */
            people_expression?: string | null;
            /** Period */
            period?: string | null;
            /**
             * Person
             * @default []
             */
            person: string[];
            /** Person Match */
            person_match?: ("and" | "or") | null;
            /** Photo Duration */
            photo_duration?: number | null;
            /** Season */
            season?: ("spring" | "summer" | "fall" | "autumn" | "winter") | null;
            /** Sharing */
            sharing?: ("just-us" | "family" | "shareable") | null;
            /** Start */
            start?: string | null;
            /** Trip Index */
            trip_index?: number | null;
            /** Year */
            year?: number | null;
            /** Years Back */
            years_back?: number | null;
        };
        /** CutShot */
        CutShot: {
            /** Alternatives */
            alternatives: components["schemas"]["Alternative"][];
            /** Asset Id */
            asset_id: string;
            /** Chapter */
            chapter: string;
            /** Day */
            day: string;
            model: components["schemas"]["ModelDecision"] | null;
            /** Moment */
            moment: string;
            /** Motion */
            motion: boolean;
            /** New Day */
            new_day: boolean;
            /** Position */
            position: number;
            /** Reason */
            reason: string;
            /** Recorded Seconds */
            recorded_seconds: number;
            /** Seconds */
            seconds: number;
            selection: components["schemas"]["SelectionPath"] | null;
            /** Source Interval */
            source_interval: [
                number,
                number
            ] | null;
            /** Start */
            start: number;
            /** Story Key */
            story_key: string;
            /** Story Title */
            story_title: string;
            /** Taken */
            taken: string;
        };
        /** Decision */
        Decision: {
            /**
             * Action
             * @enum {string}
             */
            action: "never_use" | "clear" | "forget";
            /**
             * Level
             * @default anyone
             * @enum {string}
             */
            level: "anyone" | "family" | "just-us";
        };
        /** Greeting */
        Greeting: {
            /** User */
            user: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Hold
         * @description `never_use`, `cleared:<level>` or None; `reasons` say what holds the picture, if anything.
         */
        Hold: {
            /** Can Clear */
            can_clear: boolean;
            /** Decision */
            decision: string | null;
            /** Reasons */
            reasons: string[];
        };
        /** HolidayChoice */
        HolidayChoice: {
            /** Key */
            key: string;
            /** Name */
            name: string;
        };
        /** JobProgress */
        JobProgress: {
            /** Done */
            done?: number | null;
            /** Fraction */
            fraction?: number | null;
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Phase
             * @default
             */
            phase: string;
            /**
             * Recent Asset Ids
             * @default []
             */
            recent_asset_ids: string[];
            /** Remaining Seconds */
            remaining_seconds?: number | null;
            /** Stage Remaining Seconds */
            stage_remaining_seconds?: number | null;
            /** Total */
            total?: number | null;
        };
        /** JobView */
        JobView: {
            /** Argv */
            argv: string[];
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /** Command */
            command: string;
            /** Exit Code */
            exit_code?: number | null;
            /** Finished At */
            finished_at?: number | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "cut" | "render" | "scan" | "music";
            /**
             * Meta
             * @default {}
             */
            meta: {
                [key: string]: string | number | null;
            };
            /** Pid */
            pid?: number | null;
            progress: components["schemas"]["JobProgress"];
            /** Result Run Id */
            result_run_id?: string | null;
            /** Started At */
            started_at: number;
            /**
             * Status
             * @default running
             * @enum {string}
             */
            status: "running" | "succeeded" | "failed" | "cancelled" | "interrupted";
        };
        /** Language */
        Language: {
            /** Code */
            code: string;
            /** Name */
            name: string;
        };
        /** LinkAnswer */
        LinkAnswer: {
            /** Decision */
            decision: ("confirmed" | "rejected") | null;
            /** Kind */
            kind: string;
            /** Target Id */
            target_id: string;
        };
        /** Messages */
        Messages: {
            /** Languages */
            languages: components["schemas"]["Language"][];
            /** Locale */
            locale: string;
            /** Messages */
            messages: {
                [key: string]: string;
            };
        };
        /**
         * ModelDecision
         * @description What the model polish recorded about a shot; absent when no model read the cut.
         */
        ModelDecision: {
            /** Kept Reason */
            kept_reason: string;
            /** Model Reason */
            model_reason: string;
            /** Offered Count */
            offered_count: number;
            /** Proposed Asset Id */
            proposed_asset_id: string;
            /** Replaced Asset Id */
            replaced_asset_id: string;
            /** Replacement Outcome */
            replacement_outcome: string;
            /** Seat */
            seat: string;
        };
        /** MusicTrack */
        MusicTrack: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** NamedPerson */
        NamedPerson: {
            /** Id */
            id: string;
            /** Name */
            name: string;
        };
        /** NewPerson */
        NewPerson: {
            /** Name */
            name: string;
        };
        /** PersonAnswers */
        PersonAnswers: {
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["LinkAnswer"][];
            /** Notes */
            notes?: string | null;
            /** Role */
            role?: string | null;
        };
        /** PhaseTiming */
        PhaseTiming: {
            /** Errors */
            errors: string[];
            /** Name */
            name: string;
            /** Seconds */
            seconds: number;
        };
        /** Pool */
        Pool: {
            /** Items */
            items: components["schemas"]["PoolItem"][];
            /**
             * Outside
             * @default 0
             */
            outside: number;
            /** Total */
            total: number;
        };
        /** PoolItem */
        PoolItem: {
            /** Asset Id */
            asset_id: string;
            /** Fate */
            fate: string;
            /** Favourite */
            favourite: boolean;
            hold: components["schemas"]["Hold"];
            /** In Cut */
            in_cut: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "photo" | "video" | "live";
            /** Reachable */
            reachable: boolean;
            /** Taken */
            taken: string;
        };
        /**
         * Recut
         * @description The pool's ticks: pictures the next cut must keep, and pictures it must leave out.
         */
        Recut: {
            /**
             * Exclude
             * @default []
             */
            exclude: string[];
            /**
             * Include
             * @default []
             */
            include: string[];
        };
        /** Relationship */
        Relationship: {
            /** Kind */
            kind: string;
            /** Target Id */
            target_id: string;
        };
        /**
         * RenderOptions
         * @description `runs render`'s flags; None keeps the CLI's own default.
         */
        RenderOptions: {
            /**
             * Add Date
             * @default false
             */
            add_date: boolean;
            /**
             * Add Place
             * @default false
             */
            add_place: boolean;
            /** Album */
            album?: string | null;
            /** Format */
            format?: string | null;
            /** Llm Title */
            llm_title?: boolean | null;
            /**
             * Music
             * @default auto
             */
            music: string;
            /** Music Volume */
            music_volume?: number | null;
            /** Orientation */
            orientation?: string | null;
            /**
             * Privacy Mode
             * @default false
             */
            privacy_mode: boolean;
            /** Quality */
            quality?: string | null;
            /** Resolution */
            resolution?: string | null;
            /** Revision */
            revision?: number | null;
            /** Scale Mode */
            scale_mode?: string | null;
            /** Subtitle */
            subtitle?: string | null;
            /** Title */
            title?: string | null;
            /** Transition */
            transition?: string | null;
            /**
             * Upload To Immich
             * @default false
             */
            upload_to_immich: boolean;
        };
        /** Revision */
        Revision: {
            /** Content Seconds */
            content_seconds: number;
            /** Created At */
            created_at: string;
            /** Number */
            number: number;
            /**
             * Removed
             * @default []
             */
            removed: string[];
            /**
             * Segments
             * @default {}
             */
            segments: {
                [key: string]: [
                    number,
                    number
                ];
            };
            /**
             * Swaps
             * @default {}
             */
            swaps: {
                [key: string]: string;
            };
        };
        /**
         * RevisionEdits
         * @description What the owner changed; every id must be in the cut, or a recorded sibling for a swap.
         */
        RevisionEdits: {
            /**
             * Removed
             * @default []
             */
            removed: string[];
            /**
             * Segments
             * @default {}
             */
            segments: {
                [key: string]: [
                    number,
                    number
                ];
            };
            /**
             * Swaps
             * @default {}
             */
            swaps: {
                [key: string]: string;
            };
        };
        /** Roster */
        Roster: {
            /** Flags */
            flags: components["schemas"]["RosterFlag"][];
            /** People */
            people: components["schemas"]["RosterPerson"][];
            /** Relationships */
            relationships: components["schemas"]["Choice"][];
            /** Roles */
            roles: string[];
        };
        /** RosterFlag */
        RosterFlag: {
            /** Kind */
            kind: string;
            /** Message */
            message: string;
            /** Names */
            names: string[];
            /** Person Ids */
            person_ids: string[];
        };
        /** RosterLink */
        RosterLink: {
            /** Confidence */
            confidence: number;
            /** Decision */
            decision?: string | null;
            /** Inferred */
            inferred: boolean;
            /** Kind */
            kind: string;
            /** Reverse Kind */
            reverse_kind?: string | null;
            /** Target Id */
            target_id: string;
            /** Target Name */
            target_name: string;
            /** Via */
            via: string;
        };
        /** RosterPerson */
        RosterPerson: {
            /** Birth Date */
            birth_date: string | null;
            /** Count */
            count: number;
            /** Counts Reliable */
            counts_reliable: boolean;
            /** Evidence */
            evidence: string;
            /** Links */
            links: components["schemas"]["RosterLink"][];
            /** Name */
            name: string;
            /** Notes */
            notes?: string | null;
            /** Person Id */
            person_id: string;
            /** Role */
            role?: string | null;
            /** Tier */
            tier: string;
        };
        /** RunDetail */
        RunDetail: {
            /** Child Output */
            child_output: boolean;
            /** Clips Selected */
            clips_selected: number;
            /** Completed At */
            completed_at: string | null;
            /** Created At */
            created_at: string;
            /** Date Range End */
            date_range_end: string | null;
            /** Date Range Start */
            date_range_start: string | null;
            /** Delivery Status */
            delivery_status: string;
            /** Film */
            film: boolean;
            /** Has Cut */
            has_cut: boolean;
            /** Memory Type */
            memory_type: string | null;
            /** Output Path */
            output_path: string | null;
            /** Phases */
            phases: components["schemas"]["PhaseTiming"][];
            /** Preview Asset Ids */
            preview_asset_ids: string[];
            /** Run Id */
            run_id: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Warnings */
            warnings: string[];
        };
        /** RunPage */
        RunPage: {
            /** Next Offset */
            next_offset: number | null;
            /** Runs */
            runs: components["schemas"]["RunSummary"][];
        };
        /** RunSuggestion */
        RunSuggestion: {
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /** Memory Key */
            memory_key: string;
        };
        /** RunSummary */
        RunSummary: {
            /** Created At */
            created_at: string;
            /** Date Range End */
            date_range_end: string | null;
            /** Date Range Start */
            date_range_start: string | null;
            /** Film */
            film: boolean;
            /** Memory Type */
            memory_type: string | null;
            /** Preview Asset Ids */
            preview_asset_ids: string[];
            /** Run Id */
            run_id: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
        };
        /**
         * SelectionPath
         * @description What the rules decided about a picture, in the words `runs why` prints.
         */
        SelectionPath: {
            /** Facts */
            facts: string;
            /** Kept At */
            kept_at: string | null;
            /** Left Out At */
            left_out_at: string | null;
            /** Left Out Because */
            left_out_because: string | null;
            /** Passed */
            passed: string[];
        };
        /** SessionView */
        SessionView: {
            /** Auth Enabled */
            auth_enabled: boolean;
            /** Auto Launch */
            auto_launch: boolean;
            /** Button Text */
            button_text: string | null;
            /**
             * Demo Mode Offered
             * @default false
             */
            demo_mode_offered: boolean;
            /**
             * Music Preview Offered
             * @default false
             */
            music_preview_offered: boolean;
            /** Provider */
            provider: string | null;
            /** Signed In */
            signed_in: boolean;
            /** Username */
            username: string | null;
        };
        /** ShownCommand */
        ShownCommand: {
            /** Command */
            command: string;
        };
        /** Skipped */
        Skipped: {
            /** Label */
            label: string;
            /** Rule */
            rule: string;
        };
        /** SpecialDay */
        SpecialDay: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Event Id */
            event_id: string | null;
            /** Name */
            name: string;
            /** Years Ago */
            years_ago: number | null;
        };
        /** Story */
        Story: {
            duration: components["schemas"]["StoryLength"] | null;
            /** Preparation */
            preparation: string;
            /** Stories */
            stories: components["schemas"]["StoryPart"][];
            /** Thesis */
            thesis: string;
        };
        /** StoryCarrier */
        StoryCarrier: {
            /** Asset Id */
            asset_id: string;
            /** Motion */
            motion: boolean;
            /** Reason */
            reason: string;
            /** Seconds */
            seconds: number;
            /** Taken */
            taken: string;
        };
        /** StoryLength */
        StoryLength: {
            /** Content Budget Seconds */
            content_budget_seconds: number;
            /** Requested Seconds */
            requested_seconds: number;
            /** Selected Content Seconds */
            selected_content_seconds: number;
            /** Status */
            status: string;
        };
        /** StoryPart */
        StoryPart: {
            /** Carriers */
            carriers: components["schemas"]["StoryCarrier"][];
            /** Day */
            day: string;
            /** Granted */
            granted: number;
            /** Key */
            key: string;
            /** Purpose */
            purpose: string;
            /** Title */
            title: string;
            /** Weight */
            weight: string;
        };
        /** Suggestion */
        Suggestion: {
            /** Asset Count */
            asset_count: number;
            /** Category */
            category: string;
            /** Date Range End */
            date_range_end: string;
            /** Date Range Start */
            date_range_start: string;
            /** Memory Key */
            memory_key: string;
            /** Memory Type */
            memory_type: string;
            /** Person Names */
            person_names: string[];
            /** Reason */
            reason: string;
        };
        /** Suggestions */
        Suggestions: {
            /** Candidates */
            candidates: components["schemas"]["Suggestion"][];
            /** Error */
            error: string | null;
            /** Skipped */
            skipped: components["schemas"]["Skipped"][];
        };
        /** TripChoice */
        TripChoice: {
            /** Days */
            days: number;
            /**
             * End
             * Format: date
             */
            end: string;
            /** Index */
            index: number;
            /** Pictures */
            pictures: number;
            /** Place */
            place: string;
            /**
             * Start
             * Format: date
             */
            start: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    albums_api_v1_albums_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlbumChoice"][];
                };
            };
        };
    };
    thumbnail_api_v1_assets__asset_id__thumbnail_get: {
        parameters: {
            query?: {
                size?: "thumbnail" | "preview";
            };
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    video_api_v1_assets__asset_id__video_get: {
        parameters: {
            query?: never;
            header?: {
                range?: string | null;
            };
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_attempt_api_v1_automation_attempts__attempt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    caches_api_v1_caches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheStats"][];
                };
            };
        };
    };
    clear_cache_api_v1_caches__name__clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: "analysis" | "video" | "thumbnail" | "preview";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cleared"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveConfig"];
                };
            };
        };
    };
    read_connection_api_v1_connection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
        };
    };
    save_connection_api_v1_connection_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Connection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_api_v1_connection_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionEntry"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Greeting"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_cut_api_v1_cuts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CutBrief"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cut_command_api_v1_cuts_command_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CutBrief"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShownCommand"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    holidays_api_v1_holidays_get: {
        parameters: {
            query?: {
                lang?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HolidayChoice"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    messages_api_v1_i18n_get: {
        parameters: {
            query?: {
                preference?: string;
            };
            header?: {
                "accept-language"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Messages"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    active_job_api_v1_jobs_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"] | null;
                };
            };
        };
    };
    read_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v1_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_v1_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_output_api_v1_jobs__job_id__output_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_music_api_v1_music_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_music_api_v1_music_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicTrack"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    music_api_v1_music__music_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                music_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    people_api_v1_people_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NamedPerson"][];
                };
            };
        };
    };
    face_api_v1_people__person_id__face_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_api_v1_pictures__asset_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Decision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Hold"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roster_api_v1_roster_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roster"];
                };
            };
        };
    };
    add_api_v1_roster_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewPerson"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterPerson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_people_api_v1_roster_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    answer_api_v1_roster__person_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonAnswers"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterPerson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    relate_api_v1_roster__person_id__relationships_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Relationship"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterPerson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unrelate_api_v1_roster__person_id__relationships_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Relationship"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterPerson"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_v1_runs_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                status?: ("completed" | "failed" | "running" | "cancelled" | "interrupted") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    child_output_api_v1_runs__run_id__child_output_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_cut_api_v1_runs__run_id__cut_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    film_api_v1_runs__run_id__film_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_music_preview_api_v1_runs__run_id__music_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_pool_api_v1_runs__run_id__pool_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
                reachable_only?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pool"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recut_api_v1_runs__run_id__recut_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Recut"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_render_api_v1_runs__run_id__renders_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenderOptions"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_report_api_v1_runs__run_id__report_get: {
        parameters: {
            query?: {
                include_flagged_captions?: boolean;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_revisions_api_v1_runs__run_id__revisions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_revision_api_v1_runs__run_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionEdits"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_story_api_v1_runs__run_id__story_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Story"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_view_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionView"];
                };
            };
        };
    };
    special_days_api_v1_special_days_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecialDay"][];
                };
            };
        };
    };
    suggestions_api_v1_suggestions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestions"];
                };
            };
        };
    };
    run_suggestion_api_v1_suggestions_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunSuggestion"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptView"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trips_api_v1_trips_get: {
        parameters: {
            query: {
                year: number;
                person?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripChoice"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
