import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category', label: 'Start here', collapsed: false,
      items: [
        {type: 'doc', id: 'welcome/introduction', label: 'What it does'},
        'get-started/quick-start',
        {type: 'doc', id: 'get-started/first-film', label: 'Your first film'},
        'how-it-chooses/overview',
      ],
    },
    {
      type: 'category', label: 'Make and improve films',
      items: [
        'make/improve-a-film',
        {type: 'doc', id: 'make/memory-types', label: 'Choose a memory'},
        'get-started/who-is-who',
        {type: 'doc', id: 'how-it-chooses/overrule-it', label: 'Edit the cut'},
        'how-it-chooses/length-and-filler',
        'how-it-chooses/family-audience-duplicates',
        'make/titles-maps-music',
        'make/photos-and-live-photos',
        'make/automate',
        {type: 'doc', id: 'make/free-text', label: 'A film from a sentence (experimental)'},
        {type: 'doc', id: 'make/web-ui', label: 'Find your way around the app'},
      ],
    },
    {
      type: 'category', label: 'Operate and configure',
      items: [
        'run/overview',
        'run/requirements',
        {type: 'category', label: 'Install', items: [
          {type: 'doc', id: 'run/docker', label: 'Docker Compose'},
          'run/nas', 'run/uv-pip', 'run/kubernetes', 'run/terraform',
        ]},
        {type: 'category', label: 'Access and settings', items: [
          'run/config-file', 'run/environment-variables', 'run/authentication',
          'run/network-security', 'run/privacy', 'run/multi-account',
        ]},
        {type: 'category', label: 'Storage and maintenance', items: [
          'run/database', 'run/maintenance/storage-backups',
          'run/maintenance/upgrading', 'run/maintenance/health-logs-cache',
        ]},
      ],
    },
    {
      type: 'category', label: 'Optional upgrades',
      items: [
        'better/overview',
        'get-started/what-a-gpu-or-a-model-adds',
        'better/reader', 'better/captions', 'better/inference',
        'run/hardware', 'better/gpu-render', 'better/music', 'better/measured',
      ],
    },
    {
      type: 'category', label: 'Advanced reference',
      items: [
        'reference/config-reference', 'reference/cli-reference',
        {type: 'category', label: 'CLI workflows', items: [
          'make/cli/generate', 'make/cli/prepare', 'make/cli/people',
          'make/cli/discover-days', 'make/cli/runs', 'make/cli/report', 'make/cli/pictures',
        ]},
        {type: 'category', label: 'Selection internals', items: [
          {type: 'autogenerated', dirName: 'reference/selection-internals'},
        ]},
        {type: 'category', label: 'Film and app contracts', items: [
          'reference/film-types', 'reference/generation-contract', 'reference/preparation',
          'reference/people-registry', 'reference/special-days', 'reference/output-rendering',
          'reference/media-processing', 'reference/sentence-parser',
          'reference/automation-contract', 'reference/web-ui-details',
        ]},
        {type: 'category', label: 'Services and performance', items: [
          'reference/llm-providers', 'reference/caption-service', 'reference/inference-service',
          'reference/local-audio', 'reference/performance-evidence', 'reference/benchmark-history',
          'run/reference-setup',
        ]},
        {type: 'category', label: 'Operational details', items: [
          {type: 'autogenerated', dirName: 'run/reference'},
        ]},
      ],
    },
    {
      type: 'category', label: 'Help',
      items: ['reference/troubleshooting', 'reference/faq', 'how-it-chooses/glossary'],
    },
    {
      type: 'category', label: 'Contribute',
      items: [
        'contribute/development-setup', 'contribute/architecture', 'contribute/testing',
        'contribute/ci', 'contribute/releasing', 'contribute/demo-assets',
        'contribute/code-of-conduct',
        {type: 'category', label: 'Project background', items: [
          'welcome/about', 'welcome/how-this-was-built', 'contribute/setup-matrix',
        ]},
      ],
    },
  ],
};

export default sidebars;
