"""Relationship words a title might use, in each film locale.

Each word maps to the relation type `people.relationships.owner_role` would
spell for the matching kind (casefolded: "mother", "grandchild", "best
friend", ...), whether the word is grammatically plural, and whether it
narrates from a child's point of view ("maman", "papy", "mum", "oma") rather
than naming the relation ("mère", "grand-père", "mother"). `title_guards`
refuses a perspective word outright, record or no record -- the owner's own
reading of the #1719 campaign was "too much papa et maman"; a record backing
the relation does not make the narration any less overused. Every other
relationship word still needs a fact: refused when the family record does
not back it between the people actually in the film, or when a plural word
covers only one person.

Not every word a language has for "aunt" or "cousin" is listed -- only
the vocabulary common enough that a model reaches for it unprompted, the
same words the removed prompt lists used to hand it directly.
"""

from __future__ import annotations

# word (casefold, as the model would write it) -> (relation type, is_plural, is_perspective)
RelationWord = tuple[str, bool, bool]

FAMILY_GENERIC = "family-generic"


def _word(relation_type: str, *, plural: bool = False, perspective: bool = False) -> RelationWord:
    return (relation_type, plural, perspective)


RELATIONSHIP_WORDS: dict[str, dict[str, RelationWord]] = {
    "fr": {
        "maman": _word("mother", perspective=True),
        "mère": _word("mother"),
        "papa": _word("father", perspective=True),
        "père": _word("father"),
        "fils": _word("son"),
        "fille": _word("daughter"),
        "enfant": _word("child"),
        "enfants": _word("child", plural=True),
        "le petit de": _word("child"),
        "la petite de": _word("child"),
        "petit-fils": _word("grandchild"),
        "petite-fille": _word("grandchild"),
        "petits-enfants": _word("grandchild", plural=True),
        "mamie": _word("grandparent", perspective=True),
        "papy": _word("grandparent", perspective=True),
        "mémé": _word("grandparent", perspective=True),
        "pépé": _word("grandparent", perspective=True),
        "grand-mère": _word("grandparent"),
        "grand-père": _word("grandparent"),
        "frère": _word("sibling"),
        "sœur": _word("sibling"),
        "oncle": _word("uncle"),
        "tante": _word("aunt"),
        "cousin": _word("cousin"),
        "cousine": _word("cousin"),
        "neveu": _word("nibling"),
        "nièce": _word("nibling"),
        "parrain": _word("godparent"),
        "marraine": _word("godparent"),
        "filleul": _word("godchild"),
        "filleule": _word("godchild"),
        "mari": _word("spouse"),
        "femme": _word("spouse"),
        "époux": _word("spouse"),
        "épouse": _word("spouse"),
        "meilleur ami": _word("best friend"),
        "meilleure amie": _word("best friend"),
        "ami": _word("friend"),
        "amie": _word("friend"),
        "famille": _word(FAMILY_GENERIC),
    },
    "en": {
        "mom": _word("mother", perspective=True),
        "mum": _word("mother", perspective=True),
        "mama": _word("mother", perspective=True),
        "mother": _word("mother"),
        "dad": _word("father", perspective=True),
        "father": _word("father"),
        "son": _word("son"),
        "daughter": _word("daughter"),
        "child": _word("child"),
        "children": _word("child", plural=True),
        "grandson": _word("grandchild"),
        "granddaughter": _word("grandchild"),
        "grandchildren": _word("grandchild", plural=True),
        "grandma": _word("grandparent", perspective=True),
        "grandpa": _word("grandparent", perspective=True),
        "grandmother": _word("grandparent"),
        "grandfather": _word("grandparent"),
        "brother": _word("sibling"),
        "sister": _word("sibling"),
        "uncle": _word("uncle"),
        "aunt": _word("aunt"),
        "cousin": _word("cousin"),
        "nephew": _word("nibling"),
        "niece": _word("nibling"),
        "godfather": _word("godparent"),
        "godmother": _word("godparent"),
        "godson": _word("godchild"),
        "goddaughter": _word("godchild"),
        "husband": _word("spouse"),
        "wife": _word("spouse"),
        "best friend": _word("best friend"),
        "friend": _word("friend"),
        "family": _word(FAMILY_GENERIC),
    },
    "nl": {
        "mama": _word("mother", perspective=True),
        "moeder": _word("mother"),
        "papa": _word("father", perspective=True),
        "vader": _word("father"),
        "zoon": _word("son"),
        "dochter": _word("daughter"),
        "kind": _word("child"),
        "kinderen": _word("child", plural=True),
        "kleinzoon": _word("grandchild"),
        "kleindochter": _word("grandchild"),
        "kleinkinderen": _word("grandchild", plural=True),
        "oma": _word("grandparent", perspective=True),
        "opa": _word("grandparent", perspective=True),
        "grootmoeder": _word("grandparent"),
        "grootvader": _word("grandparent"),
        "broer": _word("sibling"),
        "zus": _word("sibling"),
        "oom": _word("uncle"),
        "tante": _word("aunt"),
        "neef": _word("nibling"),
        "nicht": _word("nibling"),
        "peetvader": _word("godparent"),
        "peettante": _word("godparent"),
        "man": _word("spouse"),
        "vrouw": _word("spouse"),
        "beste vriend": _word("best friend"),
        "beste vriendin": _word("best friend"),
        "vriend": _word("friend"),
        "vriendin": _word("friend"),
        "familie": _word(FAMILY_GENERIC),
    },
    "de": {
        "mama": _word("mother", perspective=True),
        "mutter": _word("mother"),
        "papa": _word("father", perspective=True),
        "vater": _word("father"),
        "sohn": _word("son"),
        "tochter": _word("daughter"),
        "kind": _word("child"),
        "kinder": _word("child", plural=True),
        "enkel": _word("grandchild"),
        "enkelin": _word("grandchild"),
        "enkelkinder": _word("grandchild", plural=True),
        "oma": _word("grandparent", perspective=True),
        "opa": _word("grandparent", perspective=True),
        "großmutter": _word("grandparent"),
        "großvater": _word("grandparent"),
        "bruder": _word("sibling"),
        "schwester": _word("sibling"),
        "onkel": _word("uncle"),
        "tante": _word("aunt"),
        "cousin": _word("cousin"),
        "cousine": _word("cousin"),
        "nichte": _word("nibling"),
        "neffe": _word("nibling"),
        "patenonkel": _word("godparent"),
        "patin": _word("godparent"),
        "ehemann": _word("spouse"),
        "ehefrau": _word("spouse"),
        "bester freund": _word("best friend"),
        "beste freundin": _word("best friend"),
        "freund": _word("friend"),
        "freundin": _word("friend"),
        "familie": _word(FAMILY_GENERIC),
    },
    "es": {
        "mamá": _word("mother", perspective=True),
        "madre": _word("mother"),
        "papá": _word("father", perspective=True),
        "padre": _word("father"),
        "hijo": _word("son"),
        "hija": _word("daughter"),
        "hijos": _word("child", plural=True),
        "nieto": _word("grandchild"),
        "nieta": _word("grandchild"),
        "nietos": _word("grandchild", plural=True),
        "abuela": _word("grandparent", perspective=True),
        "abuelo": _word("grandparent", perspective=True),
        "hermano": _word("sibling"),
        "hermana": _word("sibling"),
        "tío": _word("uncle"),
        "tía": _word("aunt"),
        "primo": _word("cousin"),
        "prima": _word("cousin"),
        "sobrino": _word("nibling"),
        "sobrina": _word("nibling"),
        "padrino": _word("godparent"),
        "madrina": _word("godparent"),
        "esposo": _word("spouse"),
        "esposa": _word("spouse"),
        "mejor amigo": _word("best friend"),
        "mejor amiga": _word("best friend"),
        "amigo": _word("friend"),
        "amiga": _word("friend"),
        "familia": _word(FAMILY_GENERIC),
    },
    "it": {
        "mamma": _word("mother", perspective=True),
        "madre": _word("mother"),
        "papà": _word("father", perspective=True),
        "padre": _word("father"),
        "figlio": _word("son"),
        "figlia": _word("daughter"),
        "figli": _word("child", plural=True),
        "nipotino": _word("grandchild"),
        "nipotina": _word("grandchild"),
        "nonna": _word("grandparent", perspective=True),
        "nonno": _word("grandparent", perspective=True),
        "fratello": _word("sibling"),
        "sorella": _word("sibling"),
        "zio": _word("uncle"),
        "zia": _word("aunt"),
        "cugino": _word("cousin"),
        "cugina": _word("cousin"),
        "padrino": _word("godparent"),
        "madrina": _word("godparent"),
        "marito": _word("spouse"),
        "moglie": _word("spouse"),
        "migliore amico": _word("best friend"),
        "migliore amica": _word("best friend"),
        "amico": _word("friend"),
        "amica": _word("friend"),
        "famiglia": _word(FAMILY_GENERIC),
    },
    "pt-BR": {
        "mamãe": _word("mother", perspective=True),
        "mãe": _word("mother"),
        "papai": _word("father", perspective=True),
        "pai": _word("father"),
        "filho": _word("son"),
        "filha": _word("daughter"),
        "filhos": _word("child", plural=True),
        "neto": _word("grandchild"),
        "neta": _word("grandchild"),
        "netos": _word("grandchild", plural=True),
        "avó": _word("grandparent", perspective=True),
        "avô": _word("grandparent", perspective=True),
        "irmão": _word("sibling"),
        "irmã": _word("sibling"),
        "tio": _word("uncle"),
        "tia": _word("aunt"),
        "primo": _word("cousin"),
        "prima": _word("cousin"),
        "sobrinho": _word("nibling"),
        "sobrinha": _word("nibling"),
        "padrinho": _word("godparent"),
        "madrinha": _word("godparent"),
        "marido": _word("spouse"),
        "esposa": _word("spouse"),
        "melhor amigo": _word("best friend"),
        "melhor amiga": _word("best friend"),
        "amigo": _word("friend"),
        "amiga": _word("friend"),
        "família": _word(FAMILY_GENERIC),
    },
    "pt-PT": {
        "mamã": _word("mother", perspective=True),
        "mãe": _word("mother"),
        "papá": _word("father", perspective=True),
        "pai": _word("father"),
        "filho": _word("son"),
        "filha": _word("daughter"),
        "filhos": _word("child", plural=True),
        "neto": _word("grandchild"),
        "neta": _word("grandchild"),
        "netos": _word("grandchild", plural=True),
        "avó": _word("grandparent", perspective=True),
        "avô": _word("grandparent", perspective=True),
        "irmão": _word("sibling"),
        "irmã": _word("sibling"),
        "tio": _word("uncle"),
        "tia": _word("aunt"),
        "primo": _word("cousin"),
        "prima": _word("cousin"),
        "sobrinho": _word("nibling"),
        "sobrinha": _word("nibling"),
        "padrinho": _word("godparent"),
        "madrinha": _word("godparent"),
        "marido": _word("spouse"),
        "esposa": _word("spouse"),
        "melhor amigo": _word("best friend"),
        "melhor amiga": _word("best friend"),
        "amigo": _word("friend"),
        "amiga": _word("friend"),
        "família": _word(FAMILY_GENERIC),
    },
    "pl": {
        "mama": _word("mother", perspective=True),
        "matka": _word("mother"),
        "tata": _word("father", perspective=True),
        "ojciec": _word("father"),
        "syn": _word("son"),
        "córka": _word("daughter"),
        "dzieci": _word("child", plural=True),
        "wnuk": _word("grandchild"),
        "wnuczka": _word("grandchild"),
        "wnuki": _word("grandchild", plural=True),
        "babcia": _word("grandparent", perspective=True),
        "dziadek": _word("grandparent", perspective=True),
        "brat": _word("sibling"),
        "siostra": _word("sibling"),
        "wujek": _word("uncle"),
        "ciocia": _word("aunt"),
        "kuzyn": _word("cousin"),
        "kuzynka": _word("cousin"),
        "chrzestny": _word("godparent"),
        "chrzestna": _word("godparent"),
        "mąż": _word("spouse"),
        "żona": _word("spouse"),
        "najlepszy przyjaciel": _word("best friend"),
        "najlepsza przyjaciółka": _word("best friend"),
        "przyjaciel": _word("friend"),
        "przyjaciółka": _word("friend"),
        "rodzina": _word(FAMILY_GENERIC),
    },
    "sv": {
        "mamma": _word("mother", perspective=True),
        "mor": _word("mother"),
        "pappa": _word("father", perspective=True),
        "far": _word("father"),
        "son": _word("son"),
        "dotter": _word("daughter"),
        "barn": _word("child"),
        "barnen": _word("child", plural=True),
        "barnbarn": _word("grandchild"),
        "barnbarnen": _word("grandchild", plural=True),
        "mormor": _word("grandparent", perspective=True),
        "farmor": _word("grandparent", perspective=True),
        "morfar": _word("grandparent", perspective=True),
        "farfar": _word("grandparent", perspective=True),
        "bror": _word("sibling"),
        "syster": _word("sibling"),
        "farbror": _word("uncle"),
        "morbror": _word("uncle"),
        "faster": _word("aunt"),
        "moster": _word("aunt"),
        "kusin": _word("cousin"),
        "gudfar": _word("godparent"),
        "gudmor": _word("godparent"),
        "man": _word("spouse"),
        "fru": _word("spouse"),
        "bästa vän": _word("best friend"),
        "vän": _word("friend"),
        "familj": _word(FAMILY_GENERIC),
    },
    "ru": {
        "мама": _word("mother", perspective=True),
        "мать": _word("mother"),
        "папа": _word("father", perspective=True),
        "отец": _word("father"),
        "сын": _word("son"),
        "дочь": _word("daughter"),
        "дети": _word("child", plural=True),
        "внук": _word("grandchild"),
        "внучка": _word("grandchild"),
        "внуки": _word("grandchild", plural=True),
        "бабушка": _word("grandparent", perspective=True),
        "дедушка": _word("grandparent", perspective=True),
        "брат": _word("sibling"),
        "сестра": _word("sibling"),
        "дядя": _word("uncle"),
        "тётя": _word("aunt"),
        "кузен": _word("cousin"),
        "кузина": _word("cousin"),
        "крёстный": _word("godparent"),
        "крёстная": _word("godparent"),
        "муж": _word("spouse"),
        "жена": _word("spouse"),
        "лучший друг": _word("best friend"),
        "лучшая подруга": _word("best friend"),
        "друг": _word("friend"),
        "подруга": _word("friend"),
        "семья": _word(FAMILY_GENERIC),
    },
    "ja": {
        "お母さん": _word("mother", perspective=True),
        "母": _word("mother"),
        "お父さん": _word("father", perspective=True),
        "父": _word("father"),
        "息子": _word("son"),
        "娘": _word("daughter"),
        "子供たち": _word("child", plural=True),
        "孫": _word("grandchild"),
        "孫たち": _word("grandchild", plural=True),
        "おばあちゃん": _word("grandparent", perspective=True),
        "おじいちゃん": _word("grandparent", perspective=True),
        "兄": _word("sibling"),
        "姉": _word("sibling"),
        "弟": _word("sibling"),
        "妹": _word("sibling"),
        "おじさん": _word("uncle"),
        "おばさん": _word("aunt"),
        "いとこ": _word("cousin"),
        "親友": _word("best friend"),
        "友達": _word("friend"),
        "家族": _word(FAMILY_GENERIC),
    },
    "ko": {
        "엄마": _word("mother", perspective=True),
        "어머니": _word("mother"),
        "아빠": _word("father", perspective=True),
        "아버지": _word("father"),
        "아들": _word("son"),
        "딸": _word("daughter"),
        "아이들": _word("child", plural=True),
        "손자": _word("grandchild"),
        "손녀": _word("grandchild"),
        "손주들": _word("grandchild", plural=True),
        "할머니": _word("grandparent", perspective=True),
        "할아버지": _word("grandparent", perspective=True),
        "형제": _word("sibling"),
        "삼촌": _word("uncle"),
        "고모": _word("aunt"),
        "이모": _word("aunt"),
        "사촌": _word("cousin"),
        "가장 친한 친구": _word("best friend"),
        "친구": _word("friend"),
        "가족": _word(FAMILY_GENERIC),
    },
    "zh-Hans": {
        "妈妈": _word("mother", perspective=True),
        "母亲": _word("mother"),
        "爸爸": _word("father", perspective=True),
        "父亲": _word("father"),
        "儿子": _word("son"),
        "女儿": _word("daughter"),
        "孩子们": _word("child", plural=True),
        "孙子": _word("grandchild"),
        "孙女": _word("grandchild"),
        "孙辈们": _word("grandchild", plural=True),
        "奶奶": _word("grandparent", perspective=True),
        "爷爷": _word("grandparent", perspective=True),
        "兄弟": _word("sibling"),
        "姐妹": _word("sibling"),
        "叔叔": _word("uncle"),
        "阿姨": _word("aunt"),
        "表哥": _word("cousin"),
        "表姐": _word("cousin"),
        "最好的朋友": _word("best friend"),
        "朋友": _word("friend"),
        "家人": _word(FAMILY_GENERIC),
    },
}

# Family-ish types a bare "family" word is read as referring to, when nothing
# more specific is used: close relations only, not a friend or a spouse.
FAMILY_TYPES = frozenset(
    {
        "mother",
        "father",
        "parent",
        "child",
        "son",
        "daughter",
        "sibling",
        "sister",
        "brother",
        "twin",
        "grandparent",
        "grandchild",
        "uncle",
        "aunt",
        "aunt or uncle",
        "nibling",
        "cousin",
        "godparent",
        "godchild",
    }
)


def relationship_words(locale: str) -> dict[str, RelationWord]:
    """The relationship-word map for `locale`, falling back to English."""
    return RELATIONSHIP_WORDS.get(locale, RELATIONSHIP_WORDS["en"])
