"""Relationship words a title might use, in each film locale.

Each word maps to the relation type `people.relationships.owner_role` would
spell for the matching kind (casefolded: "mother", "grandchild", "best
friend", ...), plus whether the word is grammatically plural. `title_guards`
uses this to refuse a relationship word the family record does not back
between the people actually in the film, or a plural word for a relation
that covers only one person.

Not every word a language has for "aunt" or "cousin" is listed -- only
the vocabulary common enough that a model reaches for it unprompted, the
same words the removed prompt lists used to hand it directly.
"""

from __future__ import annotations

# word (casefold, as the model would write it) -> (relation type, is_plural)
RelationWord = tuple[str, bool]

FAMILY_GENERIC = "family-generic"

RELATIONSHIP_WORDS: dict[str, dict[str, RelationWord]] = {
    "fr": {
        "maman": ("mother", False),
        "mère": ("mother", False),
        "papa": ("father", False),
        "père": ("father", False),
        "fils": ("son", False),
        "fille": ("daughter", False),
        "enfant": ("child", False),
        "enfants": ("child", True),
        "le petit de": ("child", False),
        "la petite de": ("child", False),
        "petit-fils": ("grandchild", False),
        "petite-fille": ("grandchild", False),
        "petits-enfants": ("grandchild", True),
        "mamie": ("grandparent", False),
        "papy": ("grandparent", False),
        "grand-mère": ("grandparent", False),
        "grand-père": ("grandparent", False),
        "frère": ("sibling", False),
        "sœur": ("sibling", False),
        "oncle": ("uncle", False),
        "tante": ("aunt", False),
        "cousin": ("cousin", False),
        "cousine": ("cousin", False),
        "neveu": ("nibling", False),
        "nièce": ("nibling", False),
        "parrain": ("godparent", False),
        "marraine": ("godparent", False),
        "filleul": ("godchild", False),
        "filleule": ("godchild", False),
        "mari": ("spouse", False),
        "femme": ("spouse", False),
        "époux": ("spouse", False),
        "épouse": ("spouse", False),
        "meilleur ami": ("best friend", False),
        "meilleure amie": ("best friend", False),
        "ami": ("friend", False),
        "amie": ("friend", False),
        "famille": (FAMILY_GENERIC, False),
    },
    "en": {
        "mom": ("mother", False),
        "mum": ("mother", False),
        "mother": ("mother", False),
        "dad": ("father", False),
        "father": ("father", False),
        "son": ("son", False),
        "daughter": ("daughter", False),
        "child": ("child", False),
        "children": ("child", True),
        "grandson": ("grandchild", False),
        "granddaughter": ("grandchild", False),
        "grandchildren": ("grandchild", True),
        "grandma": ("grandparent", False),
        "grandpa": ("grandparent", False),
        "grandmother": ("grandparent", False),
        "grandfather": ("grandparent", False),
        "brother": ("sibling", False),
        "sister": ("sibling", False),
        "uncle": ("uncle", False),
        "aunt": ("aunt", False),
        "cousin": ("cousin", False),
        "nephew": ("nibling", False),
        "niece": ("nibling", False),
        "godfather": ("godparent", False),
        "godmother": ("godparent", False),
        "godson": ("godchild", False),
        "goddaughter": ("godchild", False),
        "husband": ("spouse", False),
        "wife": ("spouse", False),
        "best friend": ("best friend", False),
        "friend": ("friend", False),
        "family": (FAMILY_GENERIC, False),
    },
    "nl": {
        "mama": ("mother", False),
        "moeder": ("mother", False),
        "papa": ("father", False),
        "vader": ("father", False),
        "zoon": ("son", False),
        "dochter": ("daughter", False),
        "kind": ("child", False),
        "kinderen": ("child", True),
        "kleinzoon": ("grandchild", False),
        "kleindochter": ("grandchild", False),
        "kleinkinderen": ("grandchild", True),
        "oma": ("grandparent", False),
        "opa": ("grandparent", False),
        "grootmoeder": ("grandparent", False),
        "grootvader": ("grandparent", False),
        "broer": ("sibling", False),
        "zus": ("sibling", False),
        "oom": ("uncle", False),
        "tante": ("aunt", False),
        "neef": ("nibling", False),
        "nicht": ("nibling", False),
        "peetvader": ("godparent", False),
        "peettante": ("godparent", False),
        "man": ("spouse", False),
        "vrouw": ("spouse", False),
        "beste vriend": ("best friend", False),
        "beste vriendin": ("best friend", False),
        "vriend": ("friend", False),
        "vriendin": ("friend", False),
        "familie": (FAMILY_GENERIC, False),
    },
    "de": {
        "mama": ("mother", False),
        "mutter": ("mother", False),
        "papa": ("father", False),
        "vater": ("father", False),
        "sohn": ("son", False),
        "tochter": ("daughter", False),
        "kind": ("child", False),
        "kinder": ("child", True),
        "enkel": ("grandchild", False),
        "enkelin": ("grandchild", False),
        "enkelkinder": ("grandchild", True),
        "oma": ("grandparent", False),
        "opa": ("grandparent", False),
        "großmutter": ("grandparent", False),
        "großvater": ("grandparent", False),
        "bruder": ("sibling", False),
        "schwester": ("sibling", False),
        "onkel": ("uncle", False),
        "tante": ("aunt", False),
        "cousin": ("cousin", False),
        "cousine": ("cousin", False),
        "nichte": ("nibling", False),
        "neffe": ("nibling", False),
        "patenonkel": ("godparent", False),
        "patin": ("godparent", False),
        "ehemann": ("spouse", False),
        "ehefrau": ("spouse", False),
        "bester freund": ("best friend", False),
        "beste freundin": ("best friend", False),
        "freund": ("friend", False),
        "freundin": ("friend", False),
        "familie": (FAMILY_GENERIC, False),
    },
    "es": {
        "mamá": ("mother", False),
        "madre": ("mother", False),
        "papá": ("father", False),
        "padre": ("father", False),
        "hijo": ("son", False),
        "hija": ("daughter", False),
        "hijos": ("child", True),
        "nieto": ("grandchild", False),
        "nieta": ("grandchild", False),
        "nietos": ("grandchild", True),
        "abuela": ("grandparent", False),
        "abuelo": ("grandparent", False),
        "hermano": ("sibling", False),
        "hermana": ("sibling", False),
        "tío": ("uncle", False),
        "tía": ("aunt", False),
        "primo": ("cousin", False),
        "prima": ("cousin", False),
        "sobrino": ("nibling", False),
        "sobrina": ("nibling", False),
        "padrino": ("godparent", False),
        "madrina": ("godparent", False),
        "esposo": ("spouse", False),
        "esposa": ("spouse", False),
        "mejor amigo": ("best friend", False),
        "mejor amiga": ("best friend", False),
        "amigo": ("friend", False),
        "amiga": ("friend", False),
        "familia": (FAMILY_GENERIC, False),
    },
    "it": {
        "mamma": ("mother", False),
        "madre": ("mother", False),
        "papà": ("father", False),
        "padre": ("father", False),
        "figlio": ("son", False),
        "figlia": ("daughter", False),
        "figli": ("child", True),
        "nipotino": ("grandchild", False),
        "nipotina": ("grandchild", False),
        "nonna": ("grandparent", False),
        "nonno": ("grandparent", False),
        "fratello": ("sibling", False),
        "sorella": ("sibling", False),
        "zio": ("uncle", False),
        "zia": ("aunt", False),
        "cugino": ("cousin", False),
        "cugina": ("cousin", False),
        "padrino": ("godparent", False),
        "madrina": ("godparent", False),
        "marito": ("spouse", False),
        "moglie": ("spouse", False),
        "migliore amico": ("best friend", False),
        "migliore amica": ("best friend", False),
        "amico": ("friend", False),
        "amica": ("friend", False),
        "famiglia": (FAMILY_GENERIC, False),
    },
    "pt-BR": {
        "mamãe": ("mother", False),
        "mãe": ("mother", False),
        "papai": ("father", False),
        "pai": ("father", False),
        "filho": ("son", False),
        "filha": ("daughter", False),
        "filhos": ("child", True),
        "neto": ("grandchild", False),
        "neta": ("grandchild", False),
        "netos": ("grandchild", True),
        "avó": ("grandparent", False),
        "avô": ("grandparent", False),
        "irmão": ("sibling", False),
        "irmã": ("sibling", False),
        "tio": ("uncle", False),
        "tia": ("aunt", False),
        "primo": ("cousin", False),
        "prima": ("cousin", False),
        "sobrinho": ("nibling", False),
        "sobrinha": ("nibling", False),
        "padrinho": ("godparent", False),
        "madrinha": ("godparent", False),
        "marido": ("spouse", False),
        "esposa": ("spouse", False),
        "melhor amigo": ("best friend", False),
        "melhor amiga": ("best friend", False),
        "amigo": ("friend", False),
        "amiga": ("friend", False),
        "família": (FAMILY_GENERIC, False),
    },
    "pt-PT": {
        "mamã": ("mother", False),
        "mãe": ("mother", False),
        "papá": ("father", False),
        "pai": ("father", False),
        "filho": ("son", False),
        "filha": ("daughter", False),
        "filhos": ("child", True),
        "neto": ("grandchild", False),
        "neta": ("grandchild", False),
        "netos": ("grandchild", True),
        "avó": ("grandparent", False),
        "avô": ("grandparent", False),
        "irmão": ("sibling", False),
        "irmã": ("sibling", False),
        "tio": ("uncle", False),
        "tia": ("aunt", False),
        "primo": ("cousin", False),
        "prima": ("cousin", False),
        "sobrinho": ("nibling", False),
        "sobrinha": ("nibling", False),
        "padrinho": ("godparent", False),
        "madrinha": ("godparent", False),
        "marido": ("spouse", False),
        "esposa": ("spouse", False),
        "melhor amigo": ("best friend", False),
        "melhor amiga": ("best friend", False),
        "amigo": ("friend", False),
        "amiga": ("friend", False),
        "família": (FAMILY_GENERIC, False),
    },
    "pl": {
        "mama": ("mother", False),
        "matka": ("mother", False),
        "tata": ("father", False),
        "ojciec": ("father", False),
        "syn": ("son", False),
        "córka": ("daughter", False),
        "dzieci": ("child", True),
        "wnuk": ("grandchild", False),
        "wnuczka": ("grandchild", False),
        "wnuki": ("grandchild", True),
        "babcia": ("grandparent", False),
        "dziadek": ("grandparent", False),
        "brat": ("sibling", False),
        "siostra": ("sibling", False),
        "wujek": ("uncle", False),
        "ciocia": ("aunt", False),
        "kuzyn": ("cousin", False),
        "kuzynka": ("cousin", False),
        "chrzestny": ("godparent", False),
        "chrzestna": ("godparent", False),
        "mąż": ("spouse", False),
        "żona": ("spouse", False),
        "najlepszy przyjaciel": ("best friend", False),
        "najlepsza przyjaciółka": ("best friend", False),
        "przyjaciel": ("friend", False),
        "przyjaciółka": ("friend", False),
        "rodzina": (FAMILY_GENERIC, False),
    },
    "sv": {
        "mamma": ("mother", False),
        "mor": ("mother", False),
        "pappa": ("father", False),
        "far": ("father", False),
        "son": ("son", False),
        "dotter": ("daughter", False),
        "barn": ("child", False),
        "barnen": ("child", True),
        "barnbarn": ("grandchild", False),
        "barnbarnen": ("grandchild", True),
        "mormor": ("grandparent", False),
        "farmor": ("grandparent", False),
        "morfar": ("grandparent", False),
        "farfar": ("grandparent", False),
        "bror": ("sibling", False),
        "syster": ("sibling", False),
        "farbror": ("uncle", False),
        "morbror": ("uncle", False),
        "faster": ("aunt", False),
        "moster": ("aunt", False),
        "kusin": ("cousin", False),
        "gudfar": ("godparent", False),
        "gudmor": ("godparent", False),
        "man": ("spouse", False),
        "fru": ("spouse", False),
        "bästa vän": ("best friend", False),
        "vän": ("friend", False),
        "familj": (FAMILY_GENERIC, False),
    },
    "ru": {
        "мама": ("mother", False),
        "мать": ("mother", False),
        "папа": ("father", False),
        "отец": ("father", False),
        "сын": ("son", False),
        "дочь": ("daughter", False),
        "дети": ("child", True),
        "внук": ("grandchild", False),
        "внучка": ("grandchild", False),
        "внуки": ("grandchild", True),
        "бабушка": ("grandparent", False),
        "дедушка": ("grandparent", False),
        "брат": ("sibling", False),
        "сестра": ("sibling", False),
        "дядя": ("uncle", False),
        "тётя": ("aunt", False),
        "кузен": ("cousin", False),
        "кузина": ("cousin", False),
        "крёстный": ("godparent", False),
        "крёстная": ("godparent", False),
        "муж": ("spouse", False),
        "жена": ("spouse", False),
        "лучший друг": ("best friend", False),
        "лучшая подруга": ("best friend", False),
        "друг": ("friend", False),
        "подруга": ("friend", False),
        "семья": (FAMILY_GENERIC, False),
    },
    "ja": {
        "お母さん": ("mother", False),
        "母": ("mother", False),
        "お父さん": ("father", False),
        "父": ("father", False),
        "息子": ("son", False),
        "娘": ("daughter", False),
        "子供たち": ("child", True),
        "孫": ("grandchild", False),
        "孫たち": ("grandchild", True),
        "おばあちゃん": ("grandparent", False),
        "おじいちゃん": ("grandparent", False),
        "兄": ("sibling", False),
        "姉": ("sibling", False),
        "弟": ("sibling", False),
        "妹": ("sibling", False),
        "おじさん": ("uncle", False),
        "おばさん": ("aunt", False),
        "いとこ": ("cousin", False),
        "親友": ("best friend", False),
        "友達": ("friend", False),
        "家族": (FAMILY_GENERIC, False),
    },
    "ko": {
        "엄마": ("mother", False),
        "어머니": ("mother", False),
        "아빠": ("father", False),
        "아버지": ("father", False),
        "아들": ("son", False),
        "딸": ("daughter", False),
        "아이들": ("child", True),
        "손자": ("grandchild", False),
        "손녀": ("grandchild", False),
        "손주들": ("grandchild", True),
        "할머니": ("grandparent", False),
        "할아버지": ("grandparent", False),
        "형제": ("sibling", False),
        "삼촌": ("uncle", False),
        "고모": ("aunt", False),
        "이모": ("aunt", False),
        "사촌": ("cousin", False),
        "가장 친한 친구": ("best friend", False),
        "친구": ("friend", False),
        "가족": (FAMILY_GENERIC, False),
    },
    "zh-Hans": {
        "妈妈": ("mother", False),
        "爸爸": ("father", False),
        "儿子": ("son", False),
        "女儿": ("daughter", False),
        "孩子们": ("child", True),
        "孙子": ("grandchild", False),
        "孙女": ("grandchild", False),
        "孙辈们": ("grandchild", True),
        "奶奶": ("grandparent", False),
        "爷爷": ("grandparent", False),
        "兄弟": ("sibling", False),
        "姐妹": ("sibling", False),
        "叔叔": ("uncle", False),
        "阿姨": ("aunt", False),
        "表哥": ("cousin", False),
        "表姐": ("cousin", False),
        "最好的朋友": ("best friend", False),
        "朋友": ("friend", False),
        "家人": (FAMILY_GENERIC, False),
    },
}

# Family-ish types a bare "family" word is read as referring to, when nothing
# more specific is used: close relations only, not a friend or a spouse.
FAMILY_TYPES = frozenset(
    {
        "mother",
        "father",
        "parent",
        "child",
        "son",
        "daughter",
        "sibling",
        "sister",
        "brother",
        "twin",
        "grandparent",
        "grandchild",
        "uncle",
        "aunt",
        "aunt or uncle",
        "nibling",
        "cousin",
        "godparent",
        "godchild",
    }
)


def relationship_words(locale: str) -> dict[str, RelationWord]:
    """The relationship-word map for `locale`, falling back to English."""
    return RELATIONSHIP_WORDS.get(locale, RELATIONSHIP_WORDS["en"])
