"""Relationship words a title might use, in each film locale.

Each word maps to the relation type `people.relationships.owner_role` would
spell for the matching kind (casefolded: "mother", "grandchild", "best
friend", ...), whether the word is grammatically plural, and whether it
narrates from a child's point of view ("maman", "papy", "mum", "oma") rather
than naming the relation ("mère", "grand-père", "mother"). `title_guards`
refuses a perspective word outright, record or no record -- the owner's own
reading of the #1719 campaign was "too much papa et maman"; a record backing
the relation does not make the narration any less overused. Every other
relationship word still needs a fact: refused when the family record does
not back it between the people actually in the film, or when a plural word
covers only one person.

A word's type is the gendered or specific form a locale actually uses
(brother/sister, godmother/godfather) even where the stored kind is often
the generic one (sibling-of, godparent-of); `title_guards` reconciles the
two with a small alias table rather than flattening every word to the
generic type here, so a word stays the one a model would actually write.

Not every word a language has for "aunt" or "cousin" is listed -- only
the vocabulary common enough that a model reaches for it unprompted, the
same words the removed prompt lists used to hand it directly.
"""

from __future__ import annotations

# word (casefold, as the model would write it) -> (relation type, is_plural, is_perspective)
RelationWord = tuple[str, bool, bool]

FAMILY_GENERIC = "family-generic"

# A dictionary entry that exists only to protect a shorter word from firing
# inside it (longest-match-first); never itself read as a relationship claim.
NOT_A_RELATIONSHIP = "not-a-relationship"


def _word(relation_type: str, *, plural: bool = False, perspective: bool = False) -> RelationWord:
    return (relation_type, plural, perspective)


RELATIONSHIP_WORDS: dict[str, dict[str, RelationWord]] = {
    "fr": {
        "maman": _word("mother", perspective=True),
        "mère": _word("mother"),
        "papa": _word("father", perspective=True),
        "père": _word("father"),
        "parents": _word("parent", plural=True),
        "mamans": _word("mother", plural=True, perspective=True),
        "papas": _word("father", plural=True, perspective=True),
        "fils": _word("son"),
        "fille": _word("daughter"),
        "enfant": _word("child"),
        "enfants": _word("child", plural=True),
        "le petit de": _word("child"),
        "la petite de": _word("child"),
        "petit-fils": _word("grandchild"),
        "petite-fille": _word("grandchild"),
        "petits-enfants": _word("grandchild", plural=True),
        "mamie": _word("grandparent", perspective=True),
        "papy": _word("grandparent", perspective=True),
        "papi": _word("grandparent", perspective=True),
        "mamy": _word("grandparent", perspective=True),
        "mémé": _word("grandparent", perspective=True),
        "pépé": _word("grandparent", perspective=True),
        "bonne-maman": _word("grandparent", perspective=True),
        "bon-papa": _word("grandparent", perspective=True),
        "grand-mère": _word("grandparent"),
        "grand-père": _word("grandparent"),
        "grands-parents": _word("grandparent", plural=True),
        "frère": _word("brother"),
        "frères": _word("brother", plural=True),
        "sœur": _word("sister"),
        "sœurs": _word("sister", plural=True),
        "oncle": _word("uncle"),
        "oncles": _word("uncle", plural=True),
        "tonton": _word("uncle", perspective=True),
        "tante": _word("aunt"),
        "tantes": _word("aunt", plural=True),
        "tata": _word("aunt", perspective=True),
        "tatie": _word("aunt", perspective=True),
        "cousin": _word("cousin"),
        "cousine": _word("cousin"),
        "cousins": _word("cousin", plural=True),
        "cousines": _word("cousin", plural=True),
        "neveu": _word("nibling"),
        "nièce": _word("nibling"),
        "neveux": _word("nibling", plural=True),
        "nièces": _word("nibling", plural=True),
        "parrain": _word("godfather"),
        "marraine": _word("godmother"),
        "parrains": _word("godfather", plural=True),
        "marraines": _word("godmother", plural=True),
        "filleul": _word("godchild"),
        "filleule": _word("godchild"),
        "mari": _word("spouse"),
        "femme": _word("spouse"),
        "époux": _word("spouse"),
        "épouse": _word("spouse"),
        "partenaire": _word("partner"),
        "meilleur ami": _word("best friend"),
        "meilleure amie": _word("best friend"),
        "ami": _word("friend"),
        "amie": _word("friend"),
        "amis": _word("friend", plural=True),
        "amies": _word("friend", plural=True),
        "famille": _word(FAMILY_GENERIC),
    },
    "en": {
        "mom": _word("mother", perspective=True),
        "mum": _word("mother", perspective=True),
        "mama": _word("mother", perspective=True),
        "mommy": _word("mother", perspective=True),
        "mummy": _word("mother", perspective=True),
        "mother": _word("mother"),
        "moms": _word("mother", plural=True, perspective=True),
        "dad": _word("father", perspective=True),
        "daddy": _word("father", perspective=True),
        "papa": _word("father", perspective=True),
        "father": _word("father"),
        "dads": _word("father", plural=True, perspective=True),
        "parent": _word("parent"),
        "parents": _word("parent", plural=True),
        "son": _word("son"),
        "daughter": _word("daughter"),
        "child": _word("child"),
        "children": _word("child", plural=True),
        "grandson": _word("grandchild"),
        "granddaughter": _word("grandchild"),
        "grandchildren": _word("grandchild", plural=True),
        "grandma": _word("grandparent", perspective=True),
        "grandpa": _word("grandparent", perspective=True),
        "granny": _word("grandparent", perspective=True),
        "grandad": _word("grandparent", perspective=True),
        "nana": _word("grandparent", perspective=True),
        "gran": _word("grandparent", perspective=True),
        "gramps": _word("grandparent", perspective=True),
        "grandmother": _word("grandparent"),
        "grandfather": _word("grandparent"),
        "grandparents": _word("grandparent", plural=True),
        "brother": _word("brother"),
        "brothers": _word("brother", plural=True),
        "sister": _word("sister"),
        "sisters": _word("sister", plural=True),
        "sibling": _word("sibling"),
        "siblings": _word("sibling", plural=True),
        "uncle": _word("uncle"),
        "uncles": _word("uncle", plural=True),
        "aunt": _word("aunt"),
        "aunts": _word("aunt", plural=True),
        "auntie": _word("aunt", perspective=True),
        "cousin": _word("cousin"),
        "cousins": _word("cousin", plural=True),
        "nephew": _word("nibling"),
        "niece": _word("nibling"),
        "godfather": _word("godfather"),
        "godmother": _word("godmother"),
        "godson": _word("godchild"),
        "goddaughter": _word("godchild"),
        "husband": _word("spouse"),
        "wife": _word("spouse"),
        "partner": _word("partner"),
        "best friend": _word("best friend"),
        "friend": _word("friend"),
        "friends": _word("friend", plural=True),
        "family": _word(FAMILY_GENERIC),
    },
    "nl": {
        "mama": _word("mother", perspective=True),
        "mam": _word("mother", perspective=True),
        "mammie": _word("mother", perspective=True),
        "moeder": _word("mother"),
        "papa": _word("father", perspective=True),
        "pap": _word("father", perspective=True),
        "pappie": _word("father", perspective=True),
        "vader": _word("father"),
        "ouders": _word("parent", plural=True),
        "zoon": _word("son"),
        "dochter": _word("daughter"),
        "kind": _word("child"),
        "kinderen": _word("child", plural=True),
        "kleinzoon": _word("grandchild"),
        "kleindochter": _word("grandchild"),
        "kleinkinderen": _word("grandchild", plural=True),
        "oma": _word("grandparent", perspective=True),
        "opa": _word("grandparent", perspective=True),
        "omi": _word("grandparent", perspective=True),
        "opi": _word("grandparent", perspective=True),
        "bomma": _word("grandparent", perspective=True),
        "bompa": _word("grandparent", perspective=True),
        "grootmoeder": _word("grandparent"),
        "grootvader": _word("grandparent"),
        "grootouders": _word("grandparent", plural=True),
        "broer": _word("brother"),
        "broers": _word("brother", plural=True),
        "zus": _word("sister"),
        "zussen": _word("sister", plural=True),
        "oom": _word("uncle"),
        "nonkel": _word("uncle", perspective=True),
        "tante": _word("aunt"),
        "neef": _word("nibling"),
        "nicht": _word("nibling"),
        "peetvader": _word("godfather"),
        "peettante": _word("godmother"),
        "echtgenoot": _word("spouse"),
        "echtgenote": _word("spouse"),
        "partner": _word("partner"),
        "beste vriend": _word("best friend"),
        "beste vriendin": _word("best friend"),
        "vriend": _word("friend"),
        "vriendin": _word("friend"),
        "vrienden": _word("friend", plural=True),
        "familie": _word(FAMILY_GENERIC),
    },
    "de": {
        "mama": _word("mother", perspective=True),
        "mami": _word("mother", perspective=True),
        "mutti": _word("mother", perspective=True),
        "mutter": _word("mother"),
        "papa": _word("father", perspective=True),
        "papi": _word("father", perspective=True),
        "vati": _word("father", perspective=True),
        "vater": _word("father"),
        "eltern": _word("parent", plural=True),
        "sohn": _word("son"),
        "tochter": _word("daughter"),
        "kind": _word("child"),
        "kinder": _word("child", plural=True),
        "enkel": _word("grandchild"),
        "enkelin": _word("grandchild"),
        "enkelkinder": _word("grandchild", plural=True),
        "oma": _word("grandparent", perspective=True),
        "opa": _word("grandparent", perspective=True),
        "omi": _word("grandparent", perspective=True),
        "opi": _word("grandparent", perspective=True),
        "omas": _word("grandparent", plural=True, perspective=True),
        "opas": _word("grandparent", plural=True, perspective=True),
        "großmutter": _word("grandparent"),
        "großvater": _word("grandparent"),
        "großeltern": _word("grandparent", plural=True),
        "bruder": _word("brother"),
        "brüder": _word("brother", plural=True),
        "schwester": _word("sister"),
        "schwestern": _word("sister", plural=True),
        "geschwister": _word("sibling", plural=True),
        "onkel": _word("uncle"),
        "tante": _word("aunt"),
        "cousin": _word("cousin"),
        "cousine": _word("cousin"),
        "nichte": _word("nibling"),
        "neffe": _word("nibling"),
        "patenonkel": _word("godfather"),
        "patin": _word("godmother"),
        "ehemann": _word("spouse"),
        "ehefrau": _word("spouse"),
        "partner": _word("partner"),
        "bester freund": _word("best friend"),
        "beste freundin": _word("best friend"),
        "freund": _word("friend"),
        "freundin": _word("friend"),
        "familie": _word(FAMILY_GENERIC),
    },
    "es": {
        "mamá": _word("mother", perspective=True),
        "mami": _word("mother", perspective=True),
        "madre": _word("mother"),
        "papá": _word("father", perspective=True),
        "papi": _word("father", perspective=True),
        "padre": _word("father"),
        "padres": _word("parent", plural=True),
        "hijo": _word("son"),
        "hija": _word("daughter"),
        "hijos": _word("child", plural=True),
        "nieto": _word("grandchild"),
        "nieta": _word("grandchild"),
        "nietos": _word("grandchild", plural=True),
        # WHY: abuela/abuelo ARE the standard Spanish words, not a child's-eye
        # nickname next to a civil one (unlike maman vs mère) -- record-backed.
        "abuela": _word("grandparent"),
        "abuelo": _word("grandparent"),
        "abuelos": _word("grandparent", plural=True),
        # WHY: unlike the plain abuela/abuelo above, these are the
        # diminutive, affectionate forms -- a child's-eye nickname.
        "abuelita": _word("grandparent", perspective=True),
        "abuelito": _word("grandparent", perspective=True),
        "yaya": _word("grandparent", perspective=True),
        "hermano": _word("brother"),
        "hermana": _word("sister"),
        "hermanos": _word("sibling", plural=True),
        "tío": _word("uncle"),
        "tía": _word("aunt"),
        "tíos": _word("aunt or uncle", plural=True),
        "tita": _word("aunt", perspective=True),
        "tito": _word("uncle", perspective=True),
        "primo": _word("cousin"),
        "prima": _word("cousin"),
        "primos": _word("cousin", plural=True),
        "sobrino": _word("nibling"),
        "sobrina": _word("nibling"),
        "padrino": _word("godfather"),
        "madrina": _word("godmother"),
        "esposo": _word("spouse"),
        "esposa": _word("spouse"),
        "pareja": _word("partner"),
        "mejor amigo": _word("best friend"),
        "mejor amiga": _word("best friend"),
        "amigo": _word("friend"),
        "amiga": _word("friend"),
        "familia": _word(FAMILY_GENERIC),
    },
    "it": {
        "mamma": _word("mother", perspective=True),
        "madre": _word("mother"),
        "papà": _word("father", perspective=True),
        "padre": _word("father"),
        "genitori": _word("parent", plural=True),
        "figlio": _word("son"),
        "figlia": _word("daughter"),
        "figli": _word("child", plural=True),
        "nipotino": _word("grandchild"),
        "nipotina": _word("grandchild"),
        # WHY: nonna/nonno are the standard Italian words -- no separate
        # civil register exists, so a backing record is enough.
        "nonna": _word("grandparent"),
        "nonno": _word("grandparent"),
        "nonni": _word("grandparent", plural=True),
        "nonnina": _word("grandparent", perspective=True),
        "fratello": _word("brother"),
        "sorella": _word("sister"),
        "zio": _word("uncle"),
        "zia": _word("aunt"),
        "babbo": _word("father", perspective=True),
        "cugino": _word("cousin"),
        "cugina": _word("cousin"),
        "cugini": _word("cousin", plural=True),
        "padrino": _word("godfather"),
        "madrina": _word("godmother"),
        "marito": _word("spouse"),
        "moglie": _word("spouse"),
        "partner": _word("partner"),
        "migliore amico": _word("best friend"),
        "migliore amica": _word("best friend"),
        "amico": _word("friend"),
        "amica": _word("friend"),
        "famiglia": _word(FAMILY_GENERIC),
    },
    "pt-BR": {
        "mamãe": _word("mother", perspective=True),
        "mãe": _word("mother"),
        "papai": _word("father", perspective=True),
        "pai": _word("father"),
        "pais": _word("parent", plural=True),
        "filho": _word("son"),
        "filha": _word("daughter"),
        "filhos": _word("child", plural=True),
        "neto": _word("grandchild"),
        "neta": _word("grandchild"),
        "netos": _word("grandchild", plural=True),
        # WHY: avó/avô are the standard Portuguese words, not a nickname
        # beside a civil one -- record-backed, like Spanish abuela/abuelo.
        "avó": _word("grandparent"),
        "avô": _word("grandparent"),
        "avós": _word("grandparent", plural=True),
        "vovó": _word("grandparent", perspective=True),
        "vovô": _word("grandparent", perspective=True),
        "vó": _word("grandparent", perspective=True),
        "vô": _word("grandparent", perspective=True),
        "irmão": _word("brother"),
        "irmã": _word("sister"),
        "irmãos": _word("sibling", plural=True),
        "tio": _word("uncle"),
        "tia": _word("aunt"),
        "tios": _word("aunt or uncle", plural=True),
        "titia": _word("aunt", perspective=True),
        "titio": _word("uncle", perspective=True),
        "primo": _word("cousin"),
        "prima": _word("cousin"),
        "primos": _word("cousin", plural=True),
        "sobrinho": _word("nibling"),
        "sobrinha": _word("nibling"),
        "padrinho": _word("godfather"),
        "madrinha": _word("godmother"),
        "marido": _word("spouse"),
        "esposa": _word("spouse"),
        "parceiro": _word("partner"),
        "parceira": _word("partner"),
        "melhor amigo": _word("best friend"),
        "melhor amiga": _word("best friend"),
        "amigo": _word("friend"),
        "amiga": _word("friend"),
        "família": _word(FAMILY_GENERIC),
    },
    "pt-PT": {
        "mamã": _word("mother", perspective=True),
        "mãe": _word("mother"),
        "papá": _word("father", perspective=True),
        "pai": _word("father"),
        "pais": _word("parent", plural=True),
        "filho": _word("son"),
        "filha": _word("daughter"),
        "filhos": _word("child", plural=True),
        "neto": _word("grandchild"),
        "neta": _word("grandchild"),
        "netos": _word("grandchild", plural=True),
        "avó": _word("grandparent"),
        "avô": _word("grandparent"),
        "avós": _word("grandparent", plural=True),
        "avozinha": _word("grandparent", perspective=True),
        "avozinho": _word("grandparent", perspective=True),
        "irmão": _word("brother"),
        "irmã": _word("sister"),
        "irmãos": _word("sibling", plural=True),
        "tio": _word("uncle"),
        "tia": _word("aunt"),
        "tios": _word("aunt or uncle", plural=True),
        "primo": _word("cousin"),
        "prima": _word("cousin"),
        "primos": _word("cousin", plural=True),
        "sobrinho": _word("nibling"),
        "sobrinha": _word("nibling"),
        "padrinho": _word("godfather"),
        "madrinha": _word("godmother"),
        "marido": _word("spouse"),
        "esposa": _word("spouse"),
        "parceiro": _word("partner"),
        "parceira": _word("partner"),
        "melhor amigo": _word("best friend"),
        "melhor amiga": _word("best friend"),
        "amigo": _word("friend"),
        "amiga": _word("friend"),
        "família": _word(FAMILY_GENERIC),
    },
    "pl": {
        "mama": _word("mother", perspective=True),
        "mamą": _word("mother", perspective=True),
        "mamie": _word("mother", perspective=True),
        "mamusia": _word("mother", perspective=True),
        "matka": _word("mother"),
        "tata": _word("father", perspective=True),
        "tatuś": _word("father", perspective=True),
        "ojciec": _word("father"),
        "rodzice": _word("parent", plural=True),
        "syn": _word("son"),
        "córka": _word("daughter"),
        "dzieci": _word("child", plural=True),
        "wnuk": _word("grandchild"),
        "wnuczka": _word("grandchild"),
        "wnuki": _word("grandchild", plural=True),
        # WHY: babcia/dziadek are the standard Polish words, with no
        # separate civil register -- record-backed.
        "babcia": _word("grandparent"),
        "dziadek": _word("grandparent"),
        "dziadkowie": _word("grandparent", plural=True),
        "brat": _word("brother"),
        "siostra": _word("sister"),
        "wujek": _word("uncle"),
        "ciocia": _word("aunt"),
        "kuzyn": _word("cousin"),
        "kuzynka": _word("cousin"),
        "kuzyni": _word("cousin", plural=True),
        "chrzestny": _word("godfather"),
        "chrzestna": _word("godmother"),
        "mąż": _word("spouse"),
        "żona": _word("spouse"),
        "partner": _word("partner"),
        "najlepszy przyjaciel": _word("best friend"),
        "najlepsza przyjaciółka": _word("best friend"),
        "przyjaciel": _word("friend"),
        "przyjaciółka": _word("friend"),
        "rodzina": _word(FAMILY_GENERIC),
    },
    "sv": {
        "mamma": _word("mother", perspective=True),
        "mor": _word("mother"),
        "pappa": _word("father", perspective=True),
        "far": _word("father"),
        "föräldrar": _word("parent", plural=True),
        "son": _word("son"),
        "dotter": _word("daughter"),
        "barn": _word("child"),
        "barnen": _word("child", plural=True),
        "barnbarn": _word("grandchild"),
        "barnbarnen": _word("grandchild", plural=True),
        # WHY: mormor/farmor/morfar/farfar are the only standard Swedish
        # words for a maternal/paternal grandparent -- no separate civil
        # register exists, so they stay record-backed, not perspective-banned.
        "mormor": _word("grandparent"),
        "farmor": _word("grandparent"),
        "morfar": _word("grandparent"),
        "farfar": _word("grandparent"),
        "moffa": _word("grandparent", perspective=True),
        "faffa": _word("grandparent", perspective=True),
        "mommo": _word("grandparent", perspective=True),
        "fammo": _word("grandparent", perspective=True),
        "bror": _word("brother"),
        "syster": _word("sister"),
        "syskon": _word("sibling", plural=True),
        "farbror": _word("uncle"),
        "morbror": _word("uncle"),
        "faster": _word("aunt"),
        "moster": _word("aunt"),
        "kusin": _word("cousin"),
        "kusiner": _word("cousin", plural=True),
        "gudfar": _word("godfather"),
        "gudmor": _word("godmother"),
        # WHY: "man"/"fru" collide with the plain nouns "man"/"wife-as-woman"
        # in ordinary Swedish sentences; the more specific "make"/"maka"
        # (spouse) avoids flagging a title that never meant a relationship.
        "make": _word("spouse"),
        "maka": _word("spouse"),
        "partner": _word("partner"),
        "bästa vän": _word("best friend"),
        "vän": _word("friend"),
        "familj": _word(FAMILY_GENERIC),
    },
    "ru": {
        "мама": _word("mother", perspective=True),
        "мамой": _word("mother", perspective=True),
        "маме": _word("mother", perspective=True),
        "мамы": _word("mother", perspective=True),
        "мамочка": _word("mother", perspective=True),
        "мать": _word("mother"),
        "папа": _word("father", perspective=True),
        "отец": _word("father"),
        "родители": _word("parent", plural=True),
        "сын": _word("son"),
        "дочь": _word("daughter"),
        "дети": _word("child", plural=True),
        "внук": _word("grandchild"),
        "внучка": _word("grandchild"),
        "внуки": _word("grandchild", plural=True),
        # WHY: бабушка/дедушка are the standard Russian words -- record-backed.
        "бабушка": _word("grandparent"),
        "дедушка": _word("grandparent"),
        # WHY: unlike the standard бабушка/дедушка above, these are the
        # affectionate diminutive forms -- a child's-eye nickname.
        "бабуля": _word("grandparent", perspective=True),
        "деда": _word("grandparent", perspective=True),
        "брат": _word("brother"),
        "сестра": _word("sister"),
        "дядя": _word("uncle"),
        "тётя": _word("aunt"),
        "кузен": _word("cousin"),
        "кузина": _word("cousin"),
        "крёстный": _word("godfather"),
        "крёстная": _word("godmother"),
        "муж": _word("spouse"),
        "жена": _word("spouse"),
        "партнёр": _word("partner"),
        "лучший друг": _word("best friend"),
        "лучшая подруга": _word("best friend"),
        "друг": _word("friend"),
        "подруга": _word("friend"),
        "семья": _word(FAMILY_GENERIC),
    },
    "ja": {
        "ママ": _word("mother", perspective=True),
        "お母さん": _word("mother", perspective=True),
        "母さん": _word("mother", perspective=True),
        "母": _word("mother"),
        # WHY: the civil word is listed so a longest-match-first scan can
        # consume "祖母" whole, instead of "母" (mother) falsely matching
        # inside it.
        "祖母": _word("grandparent"),
        "パパ": _word("father", perspective=True),
        "お父さん": _word("father", perspective=True),
        "父": _word("father"),
        "祖父": _word("grandparent"),
        "息子": _word("son"),
        "娘": _word("daughter"),
        "子供たち": _word("child", plural=True),
        "孫": _word("grandchild"),
        "孫たち": _word("grandchild", plural=True),
        # WHY: these are the standard Japanese address words for a
        # grandparent -- record-backed, like the civil 祖母/祖父 below.
        "おばあちゃん": _word("grandparent"),
        "おじいちゃん": _word("grandparent"),
        "ばあば": _word("grandparent", perspective=True),
        "じいじ": _word("grandparent", perspective=True),
        "兄": _word("brother"),
        "姉": _word("sister"),
        "弟": _word("brother"),
        "妹": _word("sister"),
        "おじさん": _word("uncle"),
        "おばさん": _word("aunt"),
        "いとこ": _word("cousin"),
        "パートナー": _word("partner"),
        "親友": _word("best friend"),
        "友達": _word("friend"),
        "家族": _word(FAMILY_GENERIC),
    },
    "ko": {
        "엄마": _word("mother", perspective=True),
        "어머니": _word("mother"),
        "아빠": _word("father", perspective=True),
        "아버지": _word("father"),
        "아들": _word("son"),
        "딸": _word("daughter"),
        "아이들": _word("child", plural=True),
        "손자": _word("grandchild"),
        "손녀": _word("grandchild"),
        "손주들": _word("grandchild", plural=True),
        # WHY: the standard Korean words for a grandparent -- record-backed.
        "할머니": _word("grandparent"),
        "할아버지": _word("grandparent"),
        # WHY: unlike the standard 할머니/할아버지 above, these are the
        # dialectal, affectionate forms -- a child's-eye nickname.
        "할미": _word("grandparent", perspective=True),
        "할매": _word("grandparent", perspective=True),
        "형제": _word("sibling"),
        "삼촌": _word("uncle"),
        "고모": _word("aunt"),
        "이모": _word("aunt"),
        "사촌": _word("cousin"),
        "파트너": _word("partner"),
        "가장 친한 친구": _word("best friend"),
        "친구": _word("friend"),
        "가족": _word(FAMILY_GENERIC),
        # WHY: an emoticon ("이모티콘") is not an aunt ("이모"); listed so the
        # longest-match scan consumes the whole word rather than reading a
        # relation into its first syllables.
        "이모티콘": _word(NOT_A_RELATIONSHIP),
        # WHY: a strawberry ("딸기") is not a daughter ("딸"); listed so the
        # longest-match scan consumes the whole word rather than reading a
        # relation into its first syllable.
        "딸기": _word(NOT_A_RELATIONSHIP),
    },
    "zh-Hans": {
        "妈妈": _word("mother", perspective=True),
        "老妈": _word("mother", perspective=True),
        "母亲": _word("mother"),
        "祖母": _word("grandparent"),
        "爸爸": _word("father", perspective=True),
        "父亲": _word("father"),
        "祖父": _word("grandparent"),
        "儿子": _word("son"),
        "女儿": _word("daughter"),
        "孩子们": _word("child", plural=True),
        "孙子": _word("grandchild"),
        "孙女": _word("grandchild"),
        "孙辈们": _word("grandchild", plural=True),
        # WHY: the standard Chinese words for a grandparent -- record-backed.
        "奶奶": _word("grandparent"),
        "爷爷": _word("grandparent"),
        # WHY: these are the maternal-side, more dialectal grandparent
        # words -- a child's-eye nickname, unlike 奶奶/爷爷 above.
        "姥姥": _word("grandparent", perspective=True),
        "外婆": _word("grandparent", perspective=True),
        "外公": _word("grandparent", perspective=True),
        "兄弟": _word("sibling"),
        "姐妹": _word("sibling"),
        "叔叔": _word("uncle"),
        "阿姨": _word("aunt"),
        "表哥": _word("cousin"),
        "表姐": _word("cousin"),
        "伙伴": _word("partner"),
        "最好的朋友": _word("best friend"),
        "朋友": _word("friend"),
        "家人": _word(FAMILY_GENERIC),
    },
}

# A word's own type and the generic (or paired) type the stored record often
# uses instead: a gender-neutral "sibling-of" backs "brother" and "sister"
# alike, "partner-of" and "spouse-of" are read as the same claim, and a bare
# "child-of"/"parent-of" backs the gendered word a title actually writes.
TYPE_ALIASES: dict[str, tuple[str, ...]] = {
    "brother": ("sibling",),
    "sister": ("sibling",),
    "sibling": ("brother", "sister"),
    "godmother": ("godparent",),
    "godfather": ("godparent",),
    "godparent": ("godmother", "godfather"),
    "mother": ("parent",),
    "father": ("parent",),
    "parent": ("mother", "father"),
    "son": ("child",),
    "daughter": ("child",),
    "child": ("son", "daughter"),
    "aunt": ("aunt or uncle",),
    "uncle": ("aunt or uncle",),
    "partner": ("spouse",),
    "spouse": ("partner",),
}

# A relation type never required to be recorded in order to be named: the
# prompt itself says a friend is named as a friend, or by first name.
UNCONDITIONAL_TYPES = frozenset({"friend", "best friend"})

# A possessive word that speaks in the film's maker's own voice ("our
# daughter", "notre fille"). The prompt says a title never states a
# relationship to the film's maker; a relationship word right after one of
# these reads as exactly that statement, so it is refused whatever the
# record says.
MAKER_POSSESSIVES: dict[str, frozenset[str]] = {
    "fr": frozenset({"notre", "nos", "mon", "ma", "mes"}),
    "en": frozenset({"our", "my"}),
    "nl": frozenset({"onze", "mijn"}),
    "de": frozenset({"unser", "unsere", "unseren", "mein", "meine"}),
    "es": frozenset({"nuestro", "nuestra", "mi", "mis"}),
    "it": frozenset({"nostro", "nostra", "mio", "mia"}),
    "pt-BR": frozenset({"nosso", "nossa", "meu", "minha"}),
    "pt-PT": frozenset({"nosso", "nossa", "meu", "minha"}),
    "pl": frozenset({"nasz", "nasza", "mój", "moja"}),
    "sv": frozenset({"vår", "vårt", "min", "mitt"}),
    "ru": frozenset({"наш", "наша", "мой", "моя"}),
    "ja": frozenset({"私の", "僕の", "うちの"}),
    "ko": frozenset({"우리", "내"}),
    "zh-Hans": frozenset({"我的", "我们的"}),
}


def relationship_words(locale: str) -> dict[str, RelationWord]:
    """The relationship-word map for `locale`, falling back to English."""
    return RELATIONSHIP_WORDS.get(locale, RELATIONSHIP_WORDS["en"])
