#!/usr/bin/env python3
"""Run the real CLI against the hermetic fakes, for the demo's terminal recording.

Nothing here is simulated: `immich-memories generate`, `runs story` and
`runs why` run in this process, the same way the e2e tests run them, against
the fake Immich server and the scripted editorial route from `tests/e2e`. The
pictures are the CC0 fixture library; the memory is the fixture's June.

VHS records the terminal (`make demo-cli`); the Remotion `CliScene` plays it.
Under VHS (`DEMO_CLI_TIMING` set) the screen is cleared once the fakes are up, each
command is typed out, and the second each command starts at is written to
`DEMO_CLI_TIMING` as a TypeScript module, so the scene cuts the recording where the
commands really are instead of at hand-measured offsets.
"""

from __future__ import annotations

import json
import logging
import os
import sys
import tempfile
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

# The people roster resolves through the home directory, so the recording must
# not read the developer's own. Every provider override goes too.
_HOME = Path(tempfile.mkdtemp(prefix="demo-cli-home-"))
for key in list(os.environ):
    if key.startswith("IMMICH_MEMORIES_"):
        del os.environ[key]
os.environ.update(
    {
        "HOME": str(_HOME),
        "USERPROFILE": str(_HOME),
        "IMMICH_MEMORIES_AUTH__ENABLED": "false",
        "IMMICH_MEMORIES_STORAGE_SECRET": "demo-recording-session-key-8b2f6a4c0e9d",
        "IMMICH_MEMORIES_LOG_LEVEL": "error",
    }
)

# httpx logs a line per request at INFO and answers to its own logger, not the
# root level the line above sets, so a hermetic run that talks to the fake
# Immich a hundred times fills the recording with "HTTP Request: POST
# http://127.0.0.1:.../api/search/metadata". Nothing in the demo is about that.
for noisy in ("httpx", "httpcore"):
    logging.getLogger(noisy).setLevel(logging.WARNING)

import yaml  # noqa: E402
from tests.e2e.fake_editorial import install_fake_editorial_route  # noqa: E402
from tests.e2e.fake_immich import FakeImmichServer  # noqa: E402

import immich_memories.config_loader as config_loader  # noqa: E402

# Slow enough for the counted stage to last a few seconds, so the bar and the
# remaining-time estimate are on screen long enough to read.
STAGE_SECONDS = 0.9

_TIMING = os.environ.get("DEMO_CLI_TIMING")
# Typed at a person's pace for the recording; printed at once when someone runs it by hand.
_KEY_SECONDS = 0.035 if _TIMING else 0.0
# Long enough, once the command's output is on screen, for the scene to hold it and read it.
_READ_SECONDS = 2.5 if _TIMING else 0.0
_PROMPT = "\033[1;32m❯\033[0m "
_started = time.monotonic()
_marks: dict[str, float] = {}


def _clear() -> None:
    """Start the recording on an empty screen with a bare prompt, which is what VHS waits for."""
    global _started
    sys.stdout.write("\033[2J\033[3J\033[H" + _PROMPT)
    sys.stdout.flush()
    _started = time.monotonic()
    time.sleep(1.2 if _TIMING else 0.0)


def _prompt(mark: str, *words: str, fresh: bool = False) -> None:
    if not fresh:
        time.sleep(_READ_SECONDS)
        sys.stdout.write("\n" + _PROMPT)
    _marks[mark] = round(time.monotonic() - _started, 2)
    for char in " ".join(words):
        sys.stdout.write(char)
        sys.stdout.flush()
        time.sleep(_KEY_SECONDS)
    sys.stdout.write("\n")
    sys.stdout.flush()


def _write_timing() -> None:
    if not _TIMING:
        return
    _marks["end"] = round(time.monotonic() - _started, 2)
    body = "\n".join(f"  {key}: {value}," for key, value in _marks.items())
    Path(_TIMING).write_text(
        "// Generated by scripts/demo-cli-hermetic.py under `make demo-cli`: the second each\n"
        "// command starts at in cli-demo.mp4. Do not edit; re-record instead.\n"
        f"export const CLI_TIMING = {{\n{body}\n}} as const;\n"
    )


def _run(argv: list[str]) -> None:
    from immich_memories.cli import main

    sys.argv = ["immich-memories", *argv]
    try:
        main()
    except SystemExit as exit_:  # Click always exits; a non-zero code is the real signal.
        if exit_.code not in (None, 0):
            raise


def main() -> None:
    root = Path(tempfile.mkdtemp(prefix="demo-cli-"))
    server = FakeImmichServer.start(root / "fake-immich")
    try:
        cache = root / "cache"
        cache.mkdir()
        # Where a person would put it. --output names the directory and the base
        # name, not the final file: the run adds the recipe hash that makes an
        # identical rerun replace itself, and writes inside its own run
        # directory. So the recording ends on
        # ~/Videos/june-2024_<recipe>_<run>/june-2024_<recipe>.mp4, which is what
        # the last line below prints -- it reads the file the run actually wrote
        # rather than repeating what was asked for.
        out = _HOME / "Videos"
        out.mkdir()
        (root / "state").mkdir()
        config_path = root / "config.yaml"
        config_path.write_text(
            yaml.safe_dump(
                {
                    "immich": {
                        "url": server.base_url,
                        "api_key": server.api_key,
                        "api_version": "auto",
                    },
                    "output": {
                        "directory": str(out),
                        "format": "mp4",
                        "resolution": "720p",
                        "codec": "h264",
                        "hdr_mode": "sdr",
                        "quality": "low",
                    },
                    "cache": {
                        "directory": str(cache),
                        "database": str(cache / "demo.db"),
                        "video_cache_enabled": True,
                        "video_cache_max_size_gb": 1,
                        "video_cache_max_age_days": 1,
                    },
                    "upload": {"enabled": False},
                    "photos": {"enabled": True},
                    "advanced": {
                        "hardware": {"enabled": False, "backend": "none", "gpu_decode": False},
                        "musicgen": {"enabled": False},
                        "ace_step": {"enabled": False},
                    },
                },
                sort_keys=False,
            )
        )
        config_loader.Config.get_default_path = classmethod(lambda _cls: config_path)  # type: ignore[method-assign]
        config_loader.init_config_dir = lambda: root / "state"  # type: ignore[assignment]
        install_fake_editorial_route(stage_seconds=STAGE_SECONDS)

        _clear()
        _prompt(
            "generate",
            "immich-memories generate --memory-type monthly_highlights",
            "--year 2024 --month 6 --no-music --output ~/Videos/june-2024.mp4",
            fresh=True,
        )
        _run(
            [
                "generate",
                "--memory-type",
                "monthly_highlights",
                "--year",
                "2024",
                "--month",
                "6",
                "--no-music",
                "--output",
                str(out / "june-2024.mp4"),
            ]
        )

        _prompt("story", "immich-memories runs story")
        _run(["runs", "story"])

        plans = sorted(
            cache.glob("editorial-runs/*/attempts/*/plan.private.json"),
            key=lambda p: p.stat().st_mtime,
        )
        carriers = json.loads(plans[-1].read_text()).get("carriers") or [] if plans else []
        if carriers:
            asset = carriers[0]["asset_id"]
            _prompt("why", "immich-memories runs why", asset)
            _run(["runs", "why", asset])
        # And one the editor left out, so the terminal shows a reason for a "no" too.
        from tests.e2e.fake_library import DROPPED

        left_out = next(iter(DROPPED))
        _prompt("whyNot", "immich-memories runs why", left_out)
        _run(["runs", "why", left_out])
        # Typed, not run: VHS cannot show a video player. The demo cuts from
        # this line to the film itself. The name is the file the run wrote.
        written = sorted(out.rglob("*.mp4"), key=lambda p: p.stat().st_mtime)
        if written:
            _prompt("open", "open", "~/" + str(written[-1].relative_to(_HOME)))
        time.sleep(_READ_SECONDS)
        _write_timing()
    finally:
        server.close()


if __name__ == "__main__":
    main()
