// Generated by scripts/demo-cli-hermetic.py under `make demo-cli`: the second each
// command starts at in cli-demo.mp4. Do not edit; re-record instead.
export const CLI_TIMING = {
  generate: 1.21,
  story: 54.71,
  why: 58.26,
  whyNot: 62.41,
  open: 66.59,
  end: 72.02,
} as const;
