// Generated by scripts/demo-cli-hermetic.py under `make demo-cli`: the second each
// command starts at in cli-demo.mp4. Do not edit; re-record instead.
export const CLI_TIMING = {
  generate: 1.2,
  story: 37.86,
  why: 41.38,
  whyNot: 45.52,
  open: 49.67,
  end: 55.12,
} as const;
