// Generated by scripts/demo-cli-hermetic.py under `make demo-cli`: the second each
// command starts at in cli-demo.mp4. Do not edit; re-record instead.
export const CLI_TIMING = {
  generate: 1.2,
  story: 155.85,
  why: 159.28,
  whyNot: 163.27,
  open: 167.26,
  end: 172.43,
} as const;
