apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich-memories
resources:
  - ../tier-gpu
  - reader-config.yaml
components:
  - ../../components/reader-egress
patches:
  - path: deployment-reader.yaml
